.codecov.yml
.travis.yml
.tx/config
Pipfile.lock
README.md
application.py
docker-compose.yml
k8s/deploy_app.sh
k8s/helm/values.yaml
package.json
scripts/translate_schemas.py
tests/integration/questionnaire/test_questionnaire_page_titles.py

This repo has been made from the v3 branch in https://github.com/ONSdigital/eq-survey-runner, the purpose of this PR is to rename and update any files which are needed to get it running. It was also decided to move the images back to dockerhub
Make sure all references to the old branch have been removed and everything works as expected

Initial configuration changes

---

app/translations/ccs_household_gb_eng.pot
app/translations/census_household_gb_nir.pot
app/translations/census_household_gb_wls.pot
app/translations/census_individual_gb_nir.pot
app/translations/census_individual_gb_wls.pot
app/translations/messages.pot
app/translations/test_language.pot

The Copyright and Author lines include dates that are not ignored as part of translation template creation. This currently causes any build to fail.
Check if the build process executes without issue.

Update templates with 2020 as year

---

Makefile

This change should introduces the CE schema and latest changes to existing census schema

Update Makefile to load_schemas v0.0.3

---

.github/workflows/master.yml
.github/workflows/pull_request.yml

Adds a workflow step to the master action that pushes the docker image to GCR with the latest tag and the commit sha tag
Describe the steps required to test the changes (include screenshots if appropriate).

Add push to GCR to master workflow

---

.github/workflows/master.yml

Adds the GCR tags to the docker build
Look at the code. This won't run till it's in Master...

Add GCR tags to docker build for merge to master action

---

.github/workflows/master.yml

The previous pr missed a `.` that caused the build to fail. This fixes it.
Check the outcome of running these actions on branch push https://github.com/ONSdigital/eq-questionnaire-runner/actions/runs/39313571.
I will revert the run on branch to master before merging.

Fix broken docker build

---

Makefile

Update schemas repo tag to `v0.0.4`
- Are schemas from 0.0.4 loaded?

Update Questionnaire Schemas Tag

---

Makefile

A couple of PR have gone into eq-questionnaire-schema and a new release has been created, this aligns runner to use that new release

Update schema version to 0.0.7

---

Makefile
templates/partials/answer-guidance.html
templates/partials/question-definition.html
tests/functional/generate_pages.py

This should fix the Safari rendering bug.

Updated to use design system v17.0.0

---

Makefile

Updates schemas to v0.0.9
- Includes the new language property and the updated translations.
Ensure schemas are loaded correctly and work as expected

Update schemas to v0.0.9

---

Makefile

Updates the target schema version

update target schema

---

doc/architecture/decisions/0010-cookies.md

Documents the use of cookies and proposes some changes to simplify our usage of the session cookie. 
Review the document and discuss.

Add cookies decision document

---

Makefile

Updates schemas to v1.0.2 including latest content updates and changes.
Ensure schemas are loaded correctly and work as expected.

Update schema release to v0.1.2

---

Makefile

What is the context of this PR?
Updates schemas to v0.1.3 including latest content updates and changes.
How to review
Ensure schemas are loaded correctly and work as expected.

Update schema release to version v0.1.3

---

app/questionnaire/questionnaire_schema.py
app/questionnaire/router.py
app/views/handlers/section.py
scripts/run_validator.sh
test_schemas/en/test_confirmation_question_within_repeating_section.json
test_schemas/en/test_hub_and_spoke.json
test_schemas/en/test_hub_and_spoke_custom_content.json
test_schemas/en/test_is_skipping_to_end.json
test_schemas/en/test_list_change_evaluates_sections.json
test_schemas/en/test_list_collector.json
test_schemas/en/test_list_collector_driving_checkbox.json
test_schemas/en/test_list_collector_driving_question.json
test_schemas/en/test_list_collector_primary_person.json
test_schemas/en/test_list_collector_section_summary.json
test_schemas/en/test_list_summary_on_question.json
test_schemas/en/test_mutually_exclusive.json
test_schemas/en/test_relationships.json
test_schemas/en/test_repeating_section_summaries.json
test_schemas/en/test_repeating_sections_with_hub_and_spoke.json
test_schemas/en/test_section_summary.json
test_schemas/en/test_show_section_summary_on_completion.json
test_schemas/en/test_skip_condition_list.json
test_schemas/en/test_variants_first_item_in_list.json
test_schemas/en/test_variants_question.json
tests/app/questionnaire/conftest.py
tests/app/questionnaire/test_questionnaire_schema.py
tests/functional/generate_pages.py
tests/functional/spec/features/show_section_summary_on_completion/show_section_summary_on_completion.spec.js

Added the ability to have conditional section summaries so that you can choose whether a summary is shown when a section becomes complete.
Ensure the scenarios on the Trello card are satisfied.

Feature: Conditional section summaries

---

scripts/run_validator.sh
templates/partials/question.html
test_schemas/en/test_date_range.json
test_schemas/en/test_list_collector.json
test_schemas/en/test_mutually_exclusive.json
test_schemas/en/test_sum_equal_validation_against_total.json
tests/integration/questionnaire/test_questionnaire_list_collector.py

Adds the new optional warning panel to questions.
Use the `test_list_collector` questionnaire to check that the feature works. 
* [-] New static content marked up for translation

Add optional warning panel to questions

---

scripts/run_validator.sh

I accidentally committed a change which uses the feature branch for validator. This PR undoes that.

Correct validator branch

---

package.json

Functional tests are broken in Runner as chromedriver needs to be updated
Check functional tests pass

Update Chromedriver version

---

.github/workflows/codeql-analysis.yml

Adds Github code analysis
- Do we want this enabled?
- Does it work as intended?

Add GitHub code analysis

---

k8s/deploy_app.sh

Fix deployment by removing the helm --set-string command for the confirmationEmailLimit var. This will now default to 10
Test that the app deploys correctly

Remove email confirmation set string

---

templates/individual_response/confirmation-post.html

Success panel on the postal journey (screenshot attached) refers to "Individual Respondent". Change to "Individual Resident"
Describe the steps required to test the changes (include screenshots if appropriate).
Check the change is correct

Update Respondent to Resident

---

app/translations/messages.pot
templates/census-thank-you.html

Add full stops to content on the Thank You page
Check the updated content matches the screenshots attached to the Trello card.

Update Thank You Page content

---

app/translations/messages.pot
app/views/handlers/thank_you.py
tests/integration/routes/test_confirmation_email.py

Updates page title on thank you page to be more descriptive
Check tests pass. Check thank you page renders with new page title

Update thank you page title

---

templates/census-thank-you.html
templates/confirmation-email-sent.html
templates/feedback-sent.html
templates/individual_response/confirmation-post.html
templates/individual_response/confirmation-text-message.html
templates/thank-you.html

This adds and resizes tick icon in multiple templates. Change is described on this [trello card](https://trello.com/c/LKHelDnS).
Manually go through census to check if templates have changed.

Add and resize tick icons to templates

---

app/questionnaire/placeholder_parser.py
tests/app/questionnaire/test_placeholder_parser.py

This PR adds support to placeholder list sources to take into account the first item in the list.
Needed for https://github.com/ONSdigital/eq-questionnaire-schemas/pull/186
Ensure the unit test is as expected.

Update placeholder list source to support first item in list

---

templates/layouts/configs/_save-sign-out-button.html

This PR is a fix to use the correct Icon on all exit buttons
Check that the correct Icon is used on save and signout buttons

Fix sign out button icon

---

package.json
yarn.lock

Chrome driver has been updated again and because of that all our function tests are failing
Update local version to 87 and make sure the tests pass

Update chromedriver to 87

---

app/forms/error_messages.py
app/translations/messages.pot
templates/census-thank-you.html
tests/functional/spec/confirmation_email.spec.js
tests/integration/routes/test_confirmation_email.py

Minor submission page content changes needed for the Eng/Wls Household and Individual census schemas. Changes described on this [Trello card](https://trello.com/c/sNYbBMdf).
Check that the content changes match the checklist on the Trello card.

Add missing content to submission page

---

app/translations/cy/LC_MESSAGES/messages.po

Adds the latest fixes from crowdin to the Welsh static messages file.
Check the translated strings match crowdin.

Add latest Welsh static messages translation fixes

---

app/translations/messages.pot
app/views/handlers/individual_response.py

Minor content changes needed for the IR access code description. [Trello card with google sheet](https://trello.com/c/kIB864Pa).
Check that the content changes match the list in google sheet **HH/HI Changes Dec20** tab.

Add content changes to IR

---

dev-secrets.yml

Updates the dev secrets to bland/obvious values to highlight the fact that these are simply developer secrets to allow the application to be spun up quickly. 
Deploy the runner app using this branch and ensure there aren't any unexpected behaviours.

Update dev secrets

---

app/translations/cy/LC_MESSAGES/messages.po

Adds the latest fixes from crowdin to the Welsh static messages file.
Check the translated strings match crowdin.

Add latest cy static translations

---

package.json
tests/functional/wdio.conf.js
yarn.lock

Updates node modules to latest to resolve outstanding security alerts.
Verify that the functional tests work as expected.

Update node modules to latest

---

app/translations/cy/LC_MESSAGES/messages.po

What is the context of this PR?
Adds the latest fixes from crowdin to the Welsh static messages file.
How to review
Check the translated strings match crowdin.

Add the latest static Welsh translations

---

app/helpers/template_helpers.py
app/translations/messages.pot

This adds correct copyright text to NISRA census schemas as described on [Trello card](https://trello.com/c/Hc5S2ltr).
Run NISRA census themed schemas and check if text of footer data copyright is correct.

Add correct data copyright footer text (NISRA)

---

app/translations/eo/LC_MESSAGES/messages.po

Adds latest static Ulster Scots translations.
Check the translations match crowdin.

Add latest static Ulster Scots translations

---

app/translations/cy/LC_MESSAGES/messages.po

Adds an updated po file for Welsh translations
Check the Welsh translations are visible in Runner

Update Welsh po file

---

app/translations/ga/LC_MESSAGES/messages.po

Adds latest static Gaelic translations.
Check the translations match crowdin.

Add latest static Gaelic translations

---

app/translations/cy/LC_MESSAGES/messages.po

Adds the latest Welsh static translations.
Check that the updated string matches crowdin.

Update latest static cy translations

---

app/translations/eo/LC_MESSAGES/messages.po
app/translations/ga/LC_MESSAGES/messages.po

Updates the translations for NISRA Irish/Ulster Scots.
Ensure translations match Crowdin.

Update translations for NISRA

---

app/routes/questionnaire.py

Fixes the issue of redirecting to the request url detected in the CodeQL scan.
Test that the clear voluntary radio functionality works with Javascript disabled.

Fix clear radios redirect issue

---

app/translations/cy/LC_MESSAGES/messages.po
app/translations/eo/LC_MESSAGES/messages.po
app/translations/ga/LC_MESSAGES/messages.po

Adds the latest Welsh, Gaelic and Ulster Scots static translations.
Check that the updated string matches crowdin.

Update Welsh, Gaelic and Ulster Scots static file translations

---

package.json
yarn.lock

Updates chromedriver to version 89 so that functional tests pass.
Verify the build passes.

Update chromedriver to version 89 (v3-census)

---

doc/python-type-hinting.md

As a team we have committed to adding type hints throughout the Python code. This pull request defines our approach to type hinting, to ensure consistency in the codebase and avoid repeating discussions about how we apply typing.
- Review the document
- Is it clear? 
- Has anything been missed?

Add Python type hinting style guide

---

package.json
yarn.lock

Update ChromeDriver to 90
Confirm that functional tests work

Update Chromedriver to 90

---

app/authentication/authenticator.py
app/data_models/session_data.py
app/routes/flush.py
app/routes/individual_response.py
app/routes/questionnaire.py
app/routes/session.py
app/storage/metadata_parser.py
app/submitter/converter.py
app/submitter/submitter.py
app/views/handlers/confirm_email.py
app/views/handlers/submission.py
tests/app/authentication/test_authenticator.py
tests/app/data_model/test_session_store.py
tests/app/parser/conftest.py
tests/app/submitter/conftest.py
tests/app/submitter/test_submitter.py
tests/app/views/contexts/test_completed_metadata_context.py
tests/app/views/handlers/test_confirmation_email_fulfilment_request.py
tests/app/views/handlers/test_submission_handler.py
tests/functional/jwt_helper.js
tests/integration/create_token.py
tests/integration/routes/test_dump.py
tests/integration/routes/test_errors.py
tests/integration/routes/test_jwt_authentication.py
tests/integration/session/test_login.py

Questionnaire ID is census specific and can be remove
Check everything works as before and that questionnaire id has been removed from everywhere

Remove questionnaire id

---

package.json
yarn.lock

Update ChromeDriver to 92
Make sure everything passes

Update ChromeDriver to 92

---

package.json
yarn.lock

Update ChromeDriver to 93
Check functional tests pass

Update to chromedriver version 93

---

package.json
yarn.lock

Update ChromeDriver to 94.
Check functional tests pass.

Update to chromedriver version 94

---

README.md

Updates the README to include `wkhtmltopdf` as part of the install process. Removed `jsonnet` since it is no longer used.
Ensure changes are appropriate.

Update README to include wkhtmltopdf

---

test_schemas/en/test_new_routing_not_affected_by_answers_not_on_path.json
test_schemas/en/test_new_skip_condition_answer_comparison.json
test_schemas/en/test_new_skip_condition_not_set.json
test_schemas/en/test_new_skip_condition_set.json
tests/functional/spec/features/routing/answer_not_on_path.spec.js
tests/functional/spec/features/skipping/answer_comparison_skip_conditions.spec.js
tests/functional/spec/skip_conditions_not_set.spec.js
tests/functional/spec/skip_conditions_set.spec.js
tests/integration/routing/test_answer_comparison.py

test schemas with `skip_conditions` updated with new rules
Make sure following test schemas work as expected and all tests are passing
- test_skip_condition_answer_comparison.json
- test_skip_condition_not_set.json
- test_skip_condition_set.json
- test_routing_not_affected_by_answers_not_on_path.json

Update skip condition schema with new rules

---

app/data_models/app_models.py
app/data_models/questionnaire_store.py
app/storage/encrypted_questionnaire_storage.py
app/storage/storage.py
tests/app/data_model/test_app_models.py
tests/app/data_model/test_questionnaire_store.py
tests/app/storage/test_datastore.py
tests/app/storage/test_dynamodb.py
tests/app/storage/test_encrypted_questionnaire_storage.py
tests/app/submitter/conftest.py
tests/app/views/contexts/test_submitted_response_context.py
tests/app/views/handlers/conftest.py
tests/app/views/handlers/test_submission_handler.py

Add collection_exercise_sid to state
Using this branch locally and/or on GCP make sure collection-exercise-sid is added to state

Add collection exercise sid to state

---

app/data_models/list_store.py
app/questionnaire/value_source_resolver.py
app/views/handlers/individual_response.py
scripts/run_validator.sh
test_schemas/en/test_custom_page_titles.json
test_schemas/en/test_last_viewed_question_guidance.json
test_schemas/en/test_list_collector_driving_checkbox.json
test_schemas/en/test_list_collector_same_name_items.json
test_schemas/en/test_placeholder_based_on_first_item_in_list.json
test_schemas/en/test_relationships.json
test_schemas/en/test_relationships_primary.json
test_schemas/en/test_relationships_unrelated.json
tests/app/questionnaire/routing/test_when_rule_evaluator.py
tests/app/questionnaire/test_placeholder_parser.py
tests/app/questionnaire/test_placeholder_renderer.py
tests/app/questionnaire/test_value_source_resolver.py

- Update value source definition as per the validator
- Update list value source to return actual list instead of count
- Update tests and schema
- Companion PR  in [Validator](https://github.com/ONSdigital/eq-questionnaire-validator/pull/124
) 
Run schema against validator ensure all tests are working fine
Test manually list related schemas, ensure they are working as expected

Update value source definitions

---

app/submitter/submitter.py
mypy.ini

This adds type hints for `submitter.py` as it's one of the key areas of the application and we recently had a bug that could be easily avoided if we used them.
Run `./scripts/run_mypy.sh` and check if all the type hints are correct.

Add type hinting for submitter

---

package.json
yarn.lock

What is the context of this PR?
Update ChromeDriver to 95 so our tests pass.
How to review
Check functional tests pass.

Update to chromedriver version 95

---

test_schemas/en/test_benchmark_business.json

This PR adds the business test schema
There isn't really much to test here, bar launching it and making sure it has a feedback option after submission, as the checks below do the rest. The plan was to take the JSON from Author and do the minimal amount of changes to make it work, validate and add feedback, so we can use it for benchmarking. The simple fact is there are multiple things that  could be changed, ids, spelling, rules etc (but we are not reviewing the JSON as such, just it doesn't blow up ) and to quote Shaggy the content **wasn't me** anyway

Add test benchmark business schema

---

templates/partials/introduction/start-survey.html

Fixes an issue described on [this card](url). Removes button class on introduction page after DS update so there are no spacing issues.
Test relevant schema, check spacing.

Remove DS button class on introduction page

---

.github/workflows/pull_request.yml

Updates the workflow to upload the runner image to Google Artifact Registry
Create a branch with no changes, push and create a PR to trigger the workflow. When workflow actions are complete, check that the image is in the image hosting project and is correctly tagged.
Run docker pull to check the image is publicly accessible.

Adds GAR-specific push task

---

app/translations/messages.pot

The year changing to 2022 has caused translations to fail
Make sure everything passes

Update translation pot to cater for year change

---

package.json
yarn.lock

Update ChromeDriver to 96
Make sure it passes all the checks

Update Chromedriver to 96.0.0

---

app/questionnaire/placeholder_transforms.py
schemas/test/en/test_placeholder_transform.json
scripts/run_validator.sh
tests/app/questionnaire/test_placeholder_transforms.py
tests/integration/create_token.py
tests/integration/questionnaire/test_questionnaire_placeholders.py

This PR adds the transform conditional_trad_as.
Using test_placeholder_transform.json
1. Provide a trad_as in launcher and confirm it appears in the question and summary correctly
2. Don't provide a trad_as and confirm it doesn't appear in the question and summary correctly
3. (optional) as kind of the same as 2 as we deal with empty strings in optional metadata the same as not passing them. Remove trad_as from the metadata and confirm it doesn't appear in the question and summary correctly

Conditional trad as

---

schemas/test/en/test_benchmark_business.json

What it says on the tin
Ensure view submitted response is enabled

Enable view submitted response for benchmark schema

---

package.json
templates/layouts/_submit.html
yarn.lock

Makes submission guidance text bold.
Complete test_view_submitted_response schema.json to summary page, check that the text `Please submit this survey to complete it` above the submit button is bold.

Make submission guidance text bold

---

tests/app/conftest.py
tests/app/views/contexts/__init__.py
tests/app/views/contexts/conftest.py
tests/app/views/contexts/test_calculated_summary_context.py
tests/app/views/contexts/test_list_context.py
tests/app/views/contexts/test_section_summary_context.py
tests/app/views/contexts/test_submit_context.py
tests/integration/questionnaire/test_questionnaire_calculated_summary.py

Migrates tests/app/views/contexts to pytest
Check the tests make sense

Migrate tests/app/views/contexts to pytest

---

.github/workflows/pull_request.yml

Removes redundant GCR upload workflow action
Check the changes make sense

Remove GCR references

---

tests/app/views/handlers/conftest.py
tests/app/views/handlers/test_block_factory.py
tests/app/views/handlers/test_submission_handler.py
tests/app/views/handlers/test_view_submitted_response_pdf.py

Migrates tests/app/views/handlers to pytest
Check the tests make sense

Migrate tests/app/views/handlers to pytest

---

schemas/test/en/test_benchmark_business.json

In order to conduct daily benchmark tests as part of [this spike card](https://trello.com/c/9FqlydjW) test benchmark business schema needs to be simplified to one section only.
Manually test if the schema works after revamp.

Make test benchmark business schema single section

---

package.json
yarn.lock

Update ChromeDriver to 100.
Make sure it passes all the checks.

Update Chromedriver to 100.0.0

---

package.json
yarn.lock

Update to ChromeDriver v102 as the functional tests are failing
Tests pass

Update to ChromeDriver v102

---

package.json
yarn.lock

Updates Chomedriver to v105
Tests pass

Update Chromedriver to v105

---

package.json
yarn.lock

Describe what you have changed and why, link to other PRs or Issues as appropriate.
Describe the steps required to test the changes (include screenshots if appropriate).

Update chromedriver to v107

---

.github/workflows/pull_request.yml

Enable GH PR actions for feature branches

---

schemas/test/en/test_benchmark_business.json

Revert theme change made in DS v60 PR for benchmark testing
Launch `test_benchmark_business` schema and see that it has ONS theme and logos

Revert schema theme change

---

app/helpers/language_helper.py
app/routes/flush.py
app/routes/session.py
app/utilities/schema.py
tests/app/utilities/test_schema.py
tests/functional/spec/language_code.spec.js

Survey title in header (semantic html `header` element) was not translated when switching the language as it was not updated in the session cookie. This PR fixes that issue.
Extra checks added in functional test so just double check if that is correct and satisfying.

Add language toggle support for survey title

---

package.json
yarn.lock

Update Chromedriver to latest (v108)
Tests pass

Update Chromedriver to v108

---

package.json
yarn.lock

Update Chromedriver to latest (v109)
Tests pass

Update Chromedriver to v109

---

package.json
yarn.lock

Update Chromedriver to latest (v110)
Tests pass

Update to chromedriver v110

---

package.json
yarn.lock

Update Chromedriver to v111
Tests pass

Update ChromeDriver to 111

---

app/forms/questionnaire_form.py
app/questionnaire/placeholder_renderer.py
app/questionnaire/questionnaire_schema.py
app/questionnaire/schema_utils.py
app/views/contexts/question.py
app/views/contexts/summary/question.py
schemas/test/en/test_dynamic_answers_list_source.json

Describe what you have changed and why, link to other PRs or Issues as appropriate.
Describe the steps required to test the changes (include screenshots if appropriate).

Dynamic answers list source improvements

---

package.json
tests/functional/spec/textfield_suggestions.spec.js
yarn.lock

Update chromedriver to version 113.0.0
Tests pass

Update Chromedriver to version 113

---

package.json
yarn.lock

Update Chromedriver to version 114.0.0
Tests pass

Update to chromedriver v114

---

doc/python-type-hinting.md

Update/fix incorrect markdown in the type hint style guide.
Ensure markdown is accurate

Update type hint style guide markdowns

---

.schemas-version

Latest schemas: https://github.com/ONSdigital/eq-questionnaire-schemas/releases/tag/v3.77.3
Ensure the correct version is loaded when running `make build`

Schemas v3.77.3

---

app/authentication/authenticator.py

Add extra logging around session store load user without increasing log count.
Ensure the change is appropriate and not prone to error.

Add extra logging when loading user

---

package-lock.json

This update Node packages (recreates the lock) to the latest so the error in wdio during functional test runs is fixed.
Run `npm install`, check that the build passes and you can run tests locally.

Update Node packages
