ONSdigital/eq-questionnaire-runner

app/data_model/progress.py, app/data_model/progress_store.py, app/questionnaire/path_finder.py, app/questionnaire/router.py, tests/app/data_model/test_progress_store.py, tests/app/data_model/test_questionnaire_store.py, tests/app/questionnaire/test_path_finder.py, tests/app/questionnaire/test_router.py
Currently, the progress store contains duplication of `section_id` and `list_item_id` in the state. This makes the state larger than it needs to be. This PR removes these redundant data.
Instead of storing the full location object, only the block ids are now stored. I have also removed list names as we currently do not use them.
- Ensure survey progress works as expected.
- Ensure the new structure is:
```
{
"section_id": "a-section",
"block_ids": [
"block-one",
"block-two",
],
"status": "IN_PROGRESS",
"list_item_id": "dEUuoF"
}
```
=> Simplify Progress Store structure

data-source/json/test_list_collector_primary_person.json, data-source/json/test_variants_question.json, data-source/jsonnet/england-wales/individual/blocks/identity-and-health/language.jsonnet
This fixes existing routing errors detected by new validator method which checks for answer and routing values mismatches. Routing in census schemas has to be generated dynamically based on region code of given schema.
Build schemas and check if "national-identity" routing uses default "english" and "English" in case of gb_eng census schemas or "English or Welsh" in gb_wls census schemas. The main language question should now lead to national identity one. There are also two test schemas affected by this fix.
=> Fix answer and routing values mismatch errors

app/routes/flush.py, tests/integration/test_flush_data.py
Adds additional context to flush logging through use of the tx_id.
- Begin a survey through launcher, making a note of the the schema/response_id
- Answer a few questions/or none
- Save and sign out to return to launcher
- Populate the response_id/schema fields to match what survey was started with
- Switch from dumper to flusher and click flush survey data
- Confirm the log messages match the state of the answers made
=> Improve flush logging

data-source/jsonnet/england-wales/individual/blocks/personal-details/term_time_location.jsonnet
This fixes existing routing errors detected by new validator method which checks for answer and when values mismatches. It adds a fix to census schema to make it pass validator check after merge of new validator branch. 
Build schemas and check if "term-time-location" routing uses default "Yes, an address outside the UK" routing from "another-address" question.
=> Fix answer and when rules values mismatch errors

Dockerfile
Census schemas need to be brought down as part of the docker build and were accidentally removed as part of https://github.com/ONSdigital/eq-questionnaire-runner/pull/27.
Check that the schemas appear in runner when calling docker-compose up, after runner has been rebuilt.
=> Add census schemas to docker build

.github/workflows/test.yml
Docker builds are not triggered on merges to master with the current github actions setup.
Confirm the changes to the workflow file still trigger builds and you're happy with workflow name changes. You can check what the ${{ github.event.pull_request.head.ref }} for the merge/pull_request here: https://github.com/iwootten/test-action/actions
=> Trigger workflow on merge to master

.github/workflows/pull_request.yml
As per the actions docs here: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows the $GITHUB_SHA environment variable returns different values depending on the event that triggered it. On a pull_request, it is the merge commit on the branch, rather than the sha of the trigger commit. This means that the .application-version is currently incorrect on builds from our PRs.
This reverts the recent changes for the PR workflow.
Confirm that the sha in dockerhub image matches that of the commit for this PR (9dc2ccc7f1fd0350fab0c1bc6113406549f460d4). Update your docker-compose file to point to onsdigital/eq-questionnaire-runner:branch-use-head-sha-on-pr and check that /status returns the commit when brought up.
=> Use correct sha for pull requests

.github/workflows/pull_request.yml, scripts/run_validator.sh
Update runner and github actions to use the new questionnaire-validator repo.
You can check locally by using `pipenv run ./scripts/run_validator.sh` and then `pipenv run ./scripts/validate_test_schemas.sh`
Depends on [the following pr](https://github.com/ONSdigital/eq-questionnaire-validator/pull/1), which will cause actions to fail until it's merged.
=> Use new questionnaire-validator repo

.github/workflows/pull_request.yml
We currently run validator as a docker service image within our action PR workflow, which means for every validator change we make we need to update both the workflow and script to run the appropriate validator branch.
If we change to use our existing script, we don't duplicate the branch or run the risk of accidentally committing a broken PR template into runner using the wrong branch.
Decide if your happy with the change.
=> Run validator script on PR over service

app/jinja_filters.py, app/views/contexts/summary/question.py, test_schemas/en/test_placeholder_full.json, tests/app/questionnaire/test_router.py, tests/app/views/contexts/summary/test_question.py, tests/integration/integration_test_case.py, tests/integration/questionnaire/test_questionnaire_page_titles.py, tests/integration/questionnaire/test_questionnaire_placeholders.py
Fixes an issue where placeholders for Checkbox answers were not being rendered correctly on summaries. 
Use`test_placeholder_full.json` to ensure that Checkbox answers with placeholders are rendered as expected on the summary page.
=> Fix placeholder rendering of Checkbox answer on the summary pages

app/questionnaire/placeholder_parser.py, app/questionnaire/placeholder_renderer.py, app/questionnaire/plural_forms.py, app/questionnaire/schema_utils.py, app/views/handlers/block.py, app/views/handlers/question.py, test_schemas/en/test_plural_forms.json, tests/app/questionnaire/test_placeholder_parser.py, tests/app/questionnaire/test_placeholder_renderer.py, tests/app/questionnaire/test_plural_forms.py, tests/integration/questionnaire/test_questionnaire_plurals.py
Adds the ability to use plural variations of a string using babel to look up an appropriate key based on a value. Based on the proposal found [here](https://github.com/ONSdigital/eq-schema-validator/blob/v3/doc/decisions/0003-plural-forms-in-schema-text.md). Added the ability to use the length of a list as a placeholder.
Both english and welsh rule maps are added but translation is not handled as part of this card.
Depends on the [following validator PR](https://github.com/ONSdigital/eq-questionnaire-validator/pull/4), which ignores validation of text_plural labels.
Check you agree with the approach and that tests pass.
=> Implement strings based on a number of items

k8s/deploy_app.sh
Old pipelines are failing since they do not pass all the variables into `deploy_app.sh`. This PR ensures the script still works even when a variable isn't set.
Try to deploy the app without setting a variable like `GOOGLE_TAG_MANAGER_ID` and ensure it deploys as expected.
=> Allow unbound variable in deploy_app.sh

ci/deploy_app.yaml
Currently we verify app deployment success with the `wait` task. This polls the status endpoint waiting for the version returned to match the requested deploy version. This means a deployment is considered complete as soon as one pod returns the updated version, even though other pods may not have been updated yet. This issue would be more apparent in larger scale environments.
This pull request proposes using the Kubernetes deployment status to verify deployment success. `kubectl` provides a way to check for completion of a deployment via the `rollout status` command (see https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#deployment-status). This command returns a zero exit code when deployment is successful and will time out if the progress deadline is reached.
- If …
=> Verify Kubernetes deployment success on app deploy

.github/workflows/master.yml, .github/workflows/pull_request.yml, docker-compose-dev-linux.yml, docker-compose-dev-mac.yml, docker-compose.yml
Removes the publishing to GCR as part of the Github actions.
This shouldn't be merged until the new pipeline in https://github.com/ONSdigital/census-eq-concourse/pull/46 is running in Concourse.
- Check that all references to GCR are removed
=> Remove GCR image publishing

templates/partials/answers/textfield.html
This removes autocomplete from input field using lookup component. Previously there was a bug in Design System that caused autocomplete to be set to "null".
=> Remove autocomplete when using lookups

Makefile
Updates runner to use version 0.0.8 of the eq questionnaire schemas which includes the latest changes to the HH and HI schemas.
=> Update schema release to v0.0.8

ci/wait.yaml
The wait task currently explicitly checks the commit used as the version number from runner's .git/HEAD. For manual-tagged deployments, this will be a tag, not a commit hash. We can safely assume the version we ask to be deployed is deployed, so we can remove this check.
Fly the task with a reachable/unreachable endpoint and check the response is as expected.
=> Remove the version number from deployment waits

ci/README.md, ci/backup_questionnaire_state.yaml
Adds a Concourse CI task file for backing up questionnaire state. Most of the content of the task was lifted from https://github.com/ONSdigital/census-eq-concourse/blob/master/eq-backup-questionnaire-state.yaml.
Some key changes:
- `PROJECT_ID` is explicitly passed as an input to the task (rather than using the gcloud projects list command). 
- The file written on success contains the full message text for the Slack notification. This was done as `arbourd/concourse-slack-alert-resource` doesn't allow for the previous approach of setting `fields` in the notification.
- Due to the way the notifications now work, the output is only written if the export was successful. Although we could write a file on failure, this wouldn't cover other failures e.g. the project doesn't exist, and would mean …
=> Add questionnaire state backup ci task

README.md, ci/README.md, ci/deploy_app.yaml, ci/deploy_credentials.yaml, k8s/deploy_app.sh, k8s/helm/Chart.yaml, k8s/helm/templates/NOTES.txt, k8s/helm/templates/deployment.yaml, package.json
- Upgrades runner to support Helm 3.
- Specify the app deploy image and version when deploying with CI.
- `deploy_credential.yaml` now used the official `google/cloud-sdk`.
- Deploy a cluster using: https://github.com/ONSdigital/census-eq-terraform or Concourse.
- Use the `ci/README.md` to deploy the application to the cluster. Ensure the instructions are clear. 
**IMPORTANT NOTE**: If you are using an existing cluster with any deployments of runner made by Helm 2, you must use Helm 2 to delete the runner release before deploying with Helm 3. This is because Helm 3 cannot see the releases made by Helm 2 however, you cannot apply on top due to conflicts.
To delete the release with Helm 2:
1. Log in to the cluster _(You may need to add your IP to the cluster)_:
`gcloud container clusters …
=> Upgrade to Helm 3 + Use app deploy image

app/setup.py
Sets the `SameSite` property of the session cookie to `Strict`. The session cookie is a first party cookie that should never be shared with other sites. 
This is not yet possible in via the Talisman library so is done via Flask.
- Inspect the cookies and verify the `SameSite` property is set to `Strict`. 
- Verify the app works.
=> Add SameSite Strict to session cookie

scripts/run_validator.sh
Temporarily revert the validator branch to: https://github.com/ONSdigital/eq-questionnaire-validator/commit/ef9e236d8428a5661f7e7501323cc29bcf313e4c
I used the last PR branch prior to the breaking change since we don't push the commit hash on master.
Ensure all schemas validate as expected.
=> Temporarily revert validator branch

templates/list-action.tmpl, templates/listremovequestion.html, tests/functional/spec/list_collector.spec.js, tests/integration/questionnaire/test_questionnaire_list_collector.py
This changes the text on a return link to `Cancel and return to the previous page` for a multiple questions. It is part of a larger WLH schema changes card: [schemas PR](https://github.com/ONSdigital/eq-questionnaire-schemas/pull/49).
Check the overflow to make sure the change is correctly implemented. Check Google sheet attached to the card to compare individual changes.
=> WLH content changes - return link

app/forms/error_messages.py, app/translations/messages.pot, test_schemas/en/test_textarea.json, tests/functional/spec/textfield.spec.js, tests/integration/test_textarea.py
The backend message on max length for has been changed
A quick and dirty way of testing as the frontend JS will stop you entering too many characters if you use test_textarea, is either to remove JS support from your browser, or start the survey, full the box to current max_length then change and reload the schema to be less, at which point the JS will give you a minus number and let you submit
=> Correct backend error message on max length

scripts/run_validator.sh, templates/interstitial.html, test_schemas/en/test_interstitial_instruction.json, tests/integration/questionnaire/test_questionnaire_interstitial.py
Allow interviewer instructions to be added to interstitial pages. 
NB: The instruction on question pages is created as part of the onsQuestionComponent, so I've added the necessary html from the macro and we can look at possibly adding an instruction component at a later date. It's not ideal (includes question in the classname for instance), but allows us to support the feature.
Check you agree with the approach. Review https://github.com/ONSdigital/eq-questionnaire-validator/pull/39 and https://github.com/ONSdigital/eq-translations/pull/61 on which this depends.
=> Add interstitial instruction

app/submitter/converter.py, app/views/handlers/submission.py, tests/app/submitter/test_converter.py, tests/integration/routes/test_dump.py, tests/integration/routes/test_thank_you.py
This PR removes response_id from the downstream payload. The card also included removing it from logging, however it doesn't seem to currently
Check response_id has been removed from all the right places, and there is nowhere else
=> Remove response_id from downstream payload

app/helpers/template_helper.py
Updates runner with the latest changes to the page header in the design system (https://github.com/ONSdigital/design-system/pull/762). This fixes the missing Census logo and NISRA logo alignment.
Check that the Census and NISRA logos are displayed properly. You can look at https://ons-design-system.netlify.app/components/header/ to see how they should look.
=> Fix missing census logo

app/views/contexts/summary/question.py, scripts/run_validator.sh, test_schemas/en/test_custom_question_summary.json, tests/app/views/contexts/summary/test_question.py, tests/functional/spec/features/summary/custom_question_summary.spec.js
Added supports for Checkbox and Number answer types when using custom question summary.
- Ensure the concatenation is as expected when using Number/Checkbox.
=> Question summary: Add support for Checkbox and Number answer types

tests/functional/spec/features/repeating_sections/repeating_sections_with_hub_and_spoke.spec.js
Remove interim expects from middle of functional tests which serve no purpose. Currently one such expect is unnecessarily testing an age.
Check the tests continue to pass.
=> Remove expects from middle of tests

app/translations/messages.pot, templates/macros/helpers.html, tests/functional/spec/interviewer_note.spec.js
Adjusting the case on `Interviewer Note:` to be `Interviewer note:`
Check that interviewer notes are being displayed with `Interviewer note:`
=> Adjust interviwer note text

package.json, yarn.lock
Updates chromedriver to 85 to match the version of Chrome installed in the github actions. Currently all pull requests are failing as the chromedriver version doesn't match the installed version of Chrome.
- Run functional tests locally
- Check that the functional tests run successfully in this pull request
=> Update chromedriver to 85

app/questionnaire/placeholder_transforms.py, tests/app/questionnaire/test_placeholder_transforms.py
This changes how Welsh ordinals are generated. All ordinals over 20 have the "ain" suffix now. Change is described on this [Trello card](https://trello.com/c/7cBfYDWn).
Run `test_placeholder_transforms` unit test.
=> Fix Welsh ordinals over 20

app/views/handlers/list_add_question.py, test_schemas/en/test_custom_page_titles.json, tests/functional/spec/custom-page-titles.spec.js, tests/integration/questionnaire/test_questionnaire_custom_page_titles.py
List add blocks cannot use the list item id, as it does not exist. Instead, this PR overrides the _resolv_custom_page_title_vars method to return the length of the list defined by the current Location object, plus one.
Test the custom page titles for add blocks render correctly.
=> Override _resolve_custom_page_title_vars for add blocks

app/questionnaire/placeholder_parser.py, app/questionnaire/placeholder_transforms.py, scripts/run_validator.sh, test_schemas/en/test_list_collector_same_name_items.json, tests/app/questionnaire/test_placeholder_parser.py, tests/app/questionnaire/test_placeholder_transforms.py
Adds a number of transforms to placeholders for displaying middle names when first and last name match.
Changes to the `test_list_collector_same_name_items` now demonstrate both transforms at work. Full names for all householders will be displayed on the summary page if any householder has duplicate names to another, the edit page will show middle names only if that person shares their first/last name with someone else in the household.
NB. Originally I had used a new source of "list_item_id" to return the list_Item_id, but this seemed very specific and after discussion felt it better we add a "location" source. The renderer already takes both a list_item_id and location and we actually return that of list_item_id in the new transforms - to use location requires significant change to the …
=> Add transforms to support users with matching names

app/forms/questionnaire_form.py, app/forms/validators.py, test_schemas/en/test_mutually_exclusive.json, tests/app/forms/test_questionnaire_form.py, tests/app/forms/validation/test_mutually_exclusive_validator.py, tests/functional/spec/components/checkbox/mutually_exclusive/mutually_exclusive_checkbox.spec.js, tests/integration/components/mutually_exclusive/test_checkbox_single_checkbox_override.py
All mutually exclusive mandatory questions need to change to when only checkboxes are used for each answer type: 
- "Select at least one answer"
- "Select at least one answer to {question} (Using screenreaders)"
They should remain as: 
- "Enter an answer to continue" when answers of differing types are used.
Use the `test_mutually_exclusive` schema to confirm that errors displayed as expected. (New mandatory with differing answer type added)
=> Update error for mutually exclusive

package.json, yarn.lock
Updates `package.json` to use node-forge >= 0.10.0
Closes https://github.com/ONSdigital/eq-questionnaire-runner/network/alert/yarn.lock/node-forge/open
=> Update node-forge to 0.10.0

app/questionnaire/placeholder_transforms.py, tests/app/questionnaire/test_placeholder_transforms.py
Resolved an issue where the format_name transform incorrectly displayed 'None' for middle names when peoples first and last names matched.
Using `test_list_collector_same_name_items`, enter 2 people with the same name but don't enter a middle name for either. Go to the list summary and see the result.
=> Ensure middle name exists when formatting name

app/forms/validators.py, tests/app/forms/validation/test_mobile_number_validation.py
This adds new prefix to mobile number validator regex, so leading '0044' can be removed. Change is described on [this trello card](https://trello.com/c/l3y9ZHKL).
New unit test assertion has been added. Run automated tests.
=> Update telephone number for IR confirmation

gunicorn_config.py, run_app.sh
Due to the order of the env vars, when using new relic, the run commands was incorrect. To solve this, I have set the gunicorn worker class via the CLI. If this is not preferred, I can push a change to make use of an additional vars in shell script to manage the ordering.
Using `gunicorn-async`:
**Before:**
```
NEW_RELIC_CONFIG_FILE=newrelic.ini newrelic-admin run-program WEB_SERVER_WORKER_CLASS=gevent gunicorn application:application
```
**After:**
```
NEW_RELIC_CONFIG_FILE=newrelic.ini newrelic-admin run-program gunicorn application:application --worker-class gevent
```
Set `EQ_NEW_RELIC_ENABLED=True` in `.development.env` and ensure the app can be started up under different web servers.
=> Set gunicorn worker class via CLI

app/views/contexts/list_context.py, app/views/handlers/question.py, app/views/handlers/relationships/unrelated_question.py, tests/app/views/contexts/test_list_context.py, tests/integration/questionnaire/test_questionnaire_relationships_unrelated.py
Filters list summaries on unrelated question blocks so that they only include people after the current person.
- Use the `test_relationships_unrelated` schema and add some people
- Note down some of the list item ids
- Use list item ids in the `related-to-anyone-else` url and check that the page only displays peoples names after the current person - the url format is `questionnaire/relationships/people/{list_item_id}/related-to-anyone-else`. 
Note that if you use the last list item id in the `related-to-anyone-else` url it will display all people. I did consider handling this in some way, but decided not to, as this won't be possible when the unrelated routing feature is done (the location won't be routable).
* [-] New static content marked up for translation
* [-] Newly defined schema …
=> Filter list summaries on unrelated question blocks

app/forms/error_messages.py, app/translations/messages.pot, templates/partials/answers/address.html, tests/app/forms/field_handlers/test_address_handler.py, tests/app/forms/test_duration_form.py, tests/functional/spec/components/address/address.spec.js, tests/functional/spec/components/dropdown/dropdown.spec.js, tests/functional/spec/durations.spec.js, tests/integration/components/mutually_exclusive/test_checkbox_single_checkbox_override.py, tests/integration/components/mutually_exclusive/test_currency_single_checkbox_override.py, tests/integration/components/mutually_exclusive/test_date_single_checkbox_override.py, tests/integration/components/mutually_exclusive/test_duration_single_checkbox_override.py, tests/integration/components/mutually_exclusive/test_month_year_date_single_checkbox_override.py, tests/integration/components/mutually_exclusive/test_number_single_checkbox_override.py, tests/integration/components/mutually_exclusive/test_percentage_single_checkbox_override.py, tests/integration/components/mutually_exclusive/test_texarea_single_checkbox_override.py, tests/integration/components/mutually_exclusive/test_textfield_single_checkbox_override.py, tests/integration/components/mutually_exclusive/test_unit_single_checkbox_override.py, tests/integration/components/mutually_exclusive/test_year_date_single_checkbox_override.py, tests/integration/components/test_address.py
Remove `to continue` from all default error messages.
Also updates the address lookup template validation message from 'Select an address' to 'Select or manually enter an address'
Check nothing is broken by this change/tests still pass
=> Remove 'to continue' from default error messages

templates/layouts/_questionnaire.html
This adds a ga identifier to 'Choose another section and return to this later' link throughout the survey. Change is described in [this trello card](https://trello.com/c/xX0N3CdI).
Check if data-ga-action was added to questionnaire template on every page using chrome devtools.
=> Add data-ga-action identifier to "Choose another section" link

app/questionnaire/relationship_router.py, tests/app/questionnaire/test_relationship_router_unrelated.py
The "No" answer can contain other text e.g. "No, they are not related to anyone else". This change allows that by only checking that the answer starts with "No".
- Review the change and updated test
=> Make the unrelated "No" answer more flexible

app/translations/cy/LC_MESSAGES/messages.po
Updates the static translations for `cy`. Translation for `eo` and `ga` were no different.
Ensure the translations match the ones in Crowdin.
The cy version had an issue where a placeholder was added when it shouldn't have been.
To fix this, line 707 was updated from
```
msgstr[0] "Mae %(num)s broblem gyda'ch ateb"
```
To:
```
msgstr[0] "Mae problem gyda'ch ateb"
``````
=> Update static translations

app/translations/messages.pot, templates/feedback-sent.html
This marks "Done" button text on `feedback-sent` page for translation as described on [this Trello card](https://trello.com/c/Sezy5CDM). New `messages.pot` file needs uploading to Crowdin and new `.po` file needs adding to runner.
Check new messages.pot file and that feedback-sent html template text is marked for translation.
=> Add feedback sent template button text to translations template

app/translations/messages.pot, templates/partials/answers/address.html
Add missing auto-suggest properties to address lookup used by screen readers. Checked with Matt and confirmed that these are only needed for address lookups and not textfield suggestion lookups.
Try the address lookup and ensure results are grouped when search term is too broad i.e. `CF63`
To test `"There are {n} for {x}"` you will have to use the VoiceOver feature and hover over a grouped result, which should read like `There are 8 addresses for Court Road, Barry, CF63 1AB` etc.
Before:
After:
=> Add missing auto-suggest properties to address lookup

app/translations/cy/LC_MESSAGES/messages.po
Loads the latest static translations for `cy` from Crowdin
Check the translations match crowdin
The cy version had an issue where a placeholder was added when it shouldn't have been.
To fix this, line 707 was updated from
`msgstr[0] "Mae %(num)s broblem gyda'ch ateb"`
To:
`msgstr[0] "Mae problem gyda'ch ateb"`
I also had to restore the visually hidden error message which is not in Crowdin:
`msgid "Select an answer <span class=\"u-vh\">to ‘%(question_title)s’</span>"`
`msgstr "Dewiswch ateb <span class=\"u-vh\">i ‘%(question_title)s’</span>"`
=> Add latest static translations for CY

app/setup.py, templates/layouts/_base.html
A breaking googletagmanager api change means the `gtm_preview` parameter needs to be removed from the request in the snippet. The presence of this param causes the request to fail with a 404.
Check that a GTM integrated environment no longer results in a 404 for the gtm.js resource when an EQ page loads.
While investigating (and fixing) this initial issue it was found that a subsequent content-security-policy is breached by the current GTM script. The connect-src does not allow the necessary GTM domains for the scripts to function. This is not being resolved by this PR as we first need to better understand the implications of relaxing the CSP for this domain (as the relaxation should not be required for GTM to function).
=> Update googletagmanager querystring

app/translations/messages.pot, templates/individual_response/confirmation-post.html, templates/individual_response/confirmation-text-message.html, templates/individual_response/question.html, templates/partials/individual-response-guidance.html
Fixes an issue where some strings using .format in templates were not being marked for translation due to miss-placed brackets.
Check that the updated strings are being displayed correctly and any placeholders\links are still working.
=> Fix strings in templates not being marked for translation when using .format

app/translations/cy/LC_MESSAGES/messages.po, templates/partials/answers/address.html
Adds the latest fixes from crowdin to the Welsh static messages file. Fixes address lookup component error so it displays Welsh translation now.
Check the translated strings match crowdin.
=> Add latest Welsh translations and address lookup fix

Makefile, Pipfile, Pipfile.lock, scripts/run_lint_python.sh
Unpins pylint.
The recursive option is the default for isort in the latest version.
Test that linting works. Note that there is an outstanding issue that pylint is not checking all files, I have created a card for this as there is a lot of linting errors that need to be worked through.
=> Unpin pylint

templates/layouts/_questionnaire.html
This adds submit type ('SubmitType', [check DS component)](https://ons-design-system.netlify.app/components/button/) to questionnaire template button and sets it to 'timer' to prevent from double clicking on 'save and continue' and adding additional person to the household. [Trello card with bug description](https://trello.com/c/yNEM1BTY).
Inspect 'Save and continue' button using chrome dev tools. Check if button html component has a new "js-timer" class attached to it. Compare with default button. Try double clicking when adding extra person to the household (non-primary).
=> Add SubmitType equal to timer to 'save and continue' button

app/routes/questionnaire.py, tests/integration/questionnaire/test_questionnaire_relationships.py
Sending a POST request to `/questionnaire/relationships` was failing because it was falling into the non-relationship block handling code. Although we wouldn't expect this behaviour, it has been observed during testing, and should be handled properly. To fix this `POST` has been enabled on the `/questionnaire/relationships` endpoint, which consequently does the same as the `GET` and redirects to the first relationship.
I used the `test_relationships` schema, added some people and their relationships, then edited the HTML of a page in the browser Developer Tools to set `action="/questionnaire/relationships"` on the `form` element.
=> Fix 500 error on POST to /questionnaire/relationships

ci/backup_questionnaire_state.yaml
Makes the backup bucket configurable rather than using the project id. This is needed for formal environments where the backup bucket isn't in the same project as the Datastore entities being backed up.
Run a backup ci task with the new `bucket_name` variable.
=> Make CI task backup bucket configurable

ci/README.md, ci/restore_questionnaire_state.yaml
Adds a CI task for restoring questionnaire state. It mirrors the backup task with the addition of `BACKUP_NAME` for specifying which backup to restore. 
Use the README instructions to restore a backup to a GCP environment.
=> Add restore questionnaire state ci task

scripts/run_validator.sh, templates/partials/answers/textfield.html, test_schemas/en/test_textfield_suggestions.json, tests/functional/spec/textfield_suggestions.spec.js
This adds support to multiple lookups selection in [autosuggest component](https://ons-design-system.netlify.app/components/autosuggest/). This feature is described in [Trello card](https://trello.com/c/RqJlAYzx). It requires this [validator PR](https://github.com/ONSdigital/eq-questionnaire-validator/pull/86) to merge first.
New functional test was added and textfield suggestions schema was expanded. Run new functional test, run through `test_textfield_suggestions.json` manually.
=> Allow multiple lookups selection

app/setup.py, tests/integration/test_app_create.py
Adds the Google Analytics url to connect-src CSP policy.
Verify the connect-src contains the Google Analytics url.
=> Add Google Analytics to connect-src CSP policy

k8s/helm/templates/deployment.yaml
Adds a container security context definition to the Helm chart for the Runner deployment.
Deploy this branch to GCP. Test that the securityContext is created in the pod details page.
=> Add a pod securityContext that drops NET_RAW capability

app/views/handlers/individual_response.py, tests/app/views/handlers/test_individual_response_fulfilment_request.py
The postal code for IR need updating, this PR adds a missing 'A' to the string
Make sure the codes have been updated correctly
=> Update postal codes for IR

app/forms/validators.py, tests/app/forms/validation/test_date_check_validator.py
This fixes error messages when dates entered are negative, it now displays correct invalid date text for day and month incorrect numbers. This problem is described on [following Trello card](https://trello.com/c/ebDRRBVT).
Try `test_dates`, two new unit tests were added for negative number of days and months.
=> Fix error messages on dates

ci/backup_questionnaire_state.yaml, ci/deploy_credentials.yaml, ci/purge_expired_sessions.yaml, ci/restore_questionnaire_state.yaml
Due to  [deprecation](https://hub.docker.com/r/google/cloud-sdk/), update image source from google/cloud-sdk:slim gcr.io/google.com/cloudsdktool/cloud-sdk:slim 
Run the yaml locally or by the pipeline to make sure they still work
=> Update Cloud SDK location

app/translations/messages.pot, templates/layouts/_base.html
Overrides the onsSkiptToContent macro to allow translation of the link text.
Check the macro still renders correctly and the translation templates are updatd correctly
=> Override skip to content to allow translation

app/helpers/template_helpers.py, app/translations/messages.pot, tests/app/helpers/test_template_helpers.py
This removes `link`, `url` and `target` in the copyright declaration in the footer. Words 'terms and conditions' are now part of the same `text` string. Change is described on [this Trello](https://trello.com/c/jkRlGJ4x).
Check in census schemas if footer has the full `Use of address data is subject to the terms and conditions` text now.
=> Update footer copyright parameters

app/helpers/template_helpers.py
Updates the mobileLogo param to `nisra-logo-en-mobile` for the `census-nisra` application (was previously `nisra-logo-en`). This means that the size of the NISRA logo will display correctly on mobile devices.
Use a Census Nisra schema and check the NISRA logo in the header on a mobile device.
=> Update the mobileLogo for NISRA

app/setup.py, templates/layouts/_base.html, tests/integration/test_app_create.py
Updates the CSP policy to ensure it as strict as possible. 
- The `unsafe-eval` value has been removed from `script-src`. Originally this was required for Google Analytics to work, but this is no longer the case (see https://developers.google.com/tag-manager/web/csp). The tag manager snippet has been update to use the nonce compatible version.
- Values required for Google Universal Analytics have been added to the `script-src` directive (see https://developers.google.com/tag-manager/web/csp#universal_analytics_google_analytics)
- The `object-src` directive has been added with a value of `'none'`. This stops any objects being embedded (via `<object>`, `<embed>` or `<applet>` tags).
- The `base-uri` directive has been added with a value of `'none'`. This stops URIs being used in a `base` …
=> Update CSP policy

.github/workflows/pull_request.yml
Github actions now uses a version of Docker (>=20.10.0) that defaults to latest rather than all tags on push. This change explicitly sets the tag on the pull request action push.
https://docs.docker.com/engine/release-notes/#runtime-1
Check that the docker push Github action passes
=> Use tag in pull request action docker push

app/views/handlers/individual_response.py, tests/app/views/handlers/test_individual_response_fulfilment_request.py
Extends our existing logic so that we don't include an `individualCaseId` when the `case_type` is `CE`. Previously we included an `individualCaseId` when the `case_type` was not `SPG`.
Check that there is no `individualCaseId` when the `case_type` is `CE`
=> CE case_type fulfilment requests not to include individualCaseId

templates/confirmation.html, templates/feedback.html, templates/individual_response/confirmation-post.html, templates/individual_response/confirmation-text-message.html, templates/individual_response/interstitial.html, templates/interstitial.html, templates/partials/email-form.html, templates/partials/introduction/start-survey.html, templates/sectionsummary.html
Adds the `submitType: timer` field to a number of our submit buttons to protect against double clicks.
Check the templates updated match those on the Trello card.
=> Add double click protection to submit buttons

app/routes/errors.py, app/routes/individual_response.py, app/routes/questionnaire.py, app/views/handlers/individual_response.py, tests/integration/individual_response/test_individual_response.py, tests/integration/integration_test_case.py, tests/integration/routes/test_confirmation_email.py
This PR changes a 500 errors into a 400 (BadRequest) when a respondent has removed the param (email/mobile number) or has changed the hash value
Using test_confirmation_email, complete the form and send an email, now on the confirmation page try changing the email hash in the url and enter, make sure it returns a 400 rather than a 500. Now remove the email param and value completely and make sure it returns a 400 as well
Using test_individual_response add 2 people. From the hub request an individual response by text message. Now on the confirm-number page try changing the mobile phone hash in the url and enter, make sure it returns a 400 rather than a 500. Now remove the mobile phone param and value completely and make sure it returns a 400 as well. Repeat for the confirmation page (the …
=> Handle confirmation param errors for mobile numbers and email when changed or removed

app/forms/email_form.py, tests/app/forms/test_email_form.py, tests/integration/routes/test_confirmation_email.py
This PR adds a filter to the email form which strips leading and trailing white space from the email address
Using test_confirmation_email.json complete the questionnaire and enter a valid email which has leading/trailing whitespace. Make sure it submits and the email is in the right format (white space removed). Repeat on the send another email page
=> Add email filter to remove white space

app/cloud_tasks/cloud_task_publishers.py, app/data_models/fulfilment_request.py, app/publisher/publisher.py, app/views/handlers/confirmation_email.py, app/views/handlers/individual_response.py, tests/app/cloud_tasks/test_cloud_task_publishers.py, tests/app/publisher/test_publisher.py
Adds the transactionId to log lines assosciated with the individual response and confirmation fulfilment requests
Check that the assosciated log lines are correctly emitted when requesting an IR and a confirmation email
=> Add transactionId to Individual Response and Confirmation logging

.github/workflows/pull_request.yml, app/routes/session.py
Updates the sign out endpoints logic also check for the existence of the session data to prevent the error: `"AttributeError: 'NoneType' object has no attribute 'language_code'"`
No tests have been added as we could not recreate this issue from a user's perspective. The implications of this has been understood and agreed with Andrew, James and Mark.
- Ensure sign out behaviour still works as expected and this change has not adverse effects.
- Submit a census themed survey, then delete your eq-session object from Datastore and ensure that when you click `Exit` then you are redirected to the census website.
=> Update sign out logic to check for the existence of session data

app/routes/questionnaire.py, app/routes/session.py, tests/integration/integration_test_case.py, tests/integration/questionnaire/test_questionnaire_relationships.py, tests/integration/routes/test_confirmation_email.py, tests/integration/routes/test_feedback.py, tests/integration/routes/test_questionnaire.py, tests/integration/routes/test_session.py, tests/integration/routes/test_thank_you.py, tests/integration/session/test_login.py, tests/integration/session/test_sign_out_and_exit.py
Some errors were observed when HTTP HEAD requests were sent to questionnaire endpoints. It was identified that this was because a HEAD request was following the expected path of a POST request and calling form validation. In most instances this doesn't result in an error, but in the case of an optional `Date` type answer it does. 
This pull request changes the route logic so that HEAD requests follow the same path as a GET request.
- Check that the changes fix the issue
- Are there any other scenarios we should consider?
=> Handle HTTP HEAD requests

app/helpers/template_helpers.py, tests/integration/test_application_variables.py
Due to a scoping issue, the value of GTM AUTH is currently used as the value of GTM ID in the page source for the GTM scripts.
- Set the values for `EQ_GOOGLE_TAG_MANAGER_ID` and `EQ_GOOGLE_TAG_MANAGER_AUTH` then ensure they are both present in the source as expected.
- Testing this on v3.77.0 should highlight that the value of `AUTH` is duplicated and `ID` is missing from the source.
=> Fix GTM auth duplication

app/authentication/authenticator.py, app/data_models/app_models.py, app/data_models/session_store.py, app/globals.py, app/routes/session.py, app/setup.py
Changes the `get_session_store` method to only return a `SessionStore` object if a session exists. Prior to this, when a session didn't exist an 'empty' `SessionStore` object was returned with no `session_data`.
- Are the changes appropriate?
- Are there nay gaps?
=> Return None from get_session_store if no session data

.github/workflows/pull_request.yml, .github/workflows/v3_census.yml, docker-compose.yml
Updates runner to use v3-census as the base branch and Docker tags.
Ensure:
- the `v3-branch` matches the latest release
- no references were missed.
- branch protection has been set up
- The docket tag is `v3-census-latest` for clarity
=> Use v3-census branch and tags

package.json, yarn.lock
Updates chromedriver to 89 so it will match the future version of Chrome installed in the github actions. It'll prevent pull requests  from failing when the chromedriver version and the installed version of Chrome are different in future.
- Run functional tests locally
- Check that the functional tests run successfully in this pull request
=> Update chromedriver to 89

scripts/run_validator.sh
Use released validator version v1.0.0 so that future changes to validator don't break the build on the `v3-census` branch.
Check the build passes.
=> Use released validator version v1.0.0 (v3-census)

scripts/run_validator.sh
Use released validator version v1.0.0 so that future changes to validator don't break the build.
Check the build passes.
=> Use released validator version v1.0.0

Pipfile.lock
This updates sdc-cryptography to version 1.0.9 as per requirement on [this Trello card](https://trello.com/c/A7gsw32u). All unpinned dependencies were also updated when using `pipenv update` command.
Check if tests pass and updated packages are working as expected.
=> Update sdc-cryptography & dependencies 

Pipfile, Pipfile.lock, app/translations/messages.pot
simplejson is currently included as a dependency of an unused Flask-Themes2 module. This PR adds simplejson as its own dependency and remove Flask-Themes2
N.B. As Babel has updated as well I have had to run translations
Update/rebuild you env and make sure everything works
=> Remove Flask-Themes2 and add simplejson

app/setup.py, tests/integration/integration_test_case.py
This moves imports to top-level in `setup.py` and `test_integration_case.py` as requested on this [Trello](https://trello.com/c/ILGQUcJW). It also fixes error `individual_response_blueprint` config setup which got highlighted after completing move imports task. `test_roles.py` is the only file were we still ignore top-level imports rule.
To find places where `pylint` top level imports check is ignored search for `pylint: disable=import-outside-toplevel`.
=> Move remaining imports to top-level

app/authentication/authenticator.py, app/data_models/session_data.py, app/routes/flush.py, app/routes/session.py, app/storage/metadata_parser.py, app/submitter/converter.py, app/submitter/submitter.py, app/views/handlers/submission.py, tests/app/parser/conftest.py, tests/app/submitter/test_submitter.py, tests/app/views/handlers/test_submission_handler.py, tests/integration/session/test_login.py
For census case_id was made optional, this PR reverts it back to mandatory for business surveys
Make sure everything still works, that case_id is now mandatory and tests have been changed. Also check that condition statements and defaults involving case_id have all been updated and nothing has been missed
=> Make case_id mandatory

app/routes/flush.py, tests/integration/test_flush_data.py
On flushing the submission_language_code should be set to -9
Check that the submission_language_code is -9 when flushing
=> Set submission_language_code to -9 on flush

templates/partials/answers/date.html, test_schemas/en/test_dates.json, tests/functional/base_pages/question.page.js, tests/functional/spec/dates.spec.js
For date questions, if an answer label is provided then it should be used for the Design System component legend for date field labels. Otherwise, the question title should be used, and the field should be visually hidden.
Use `test-dates` to check that the answer label is displayed in the date field label if provided. Check that no field is displayed if no answer label is present.
=> Use answer labels for date field labels if provided

scripts/run_validator.sh, test_schemas/en/test_big_list_naughty_strings.json, test_schemas/en/test_checkbox_detail_answer_multiple.json, test_schemas/en/test_checkbox_detail_answer_numeric.json, test_schemas/en/test_currency.json, test_schemas/en/test_instructions.json, test_schemas/en/test_interstitial_page.json, test_schemas/en/test_interviewer_note.json, test_schemas/en/test_percentage.json, test_schemas/en/test_placeholder_metadata.json, test_schemas/en/test_placeholder_playback_list.json, test_schemas/en/test_question_description.json, test_schemas/en/test_question_title_in_error.json, test_schemas/en/test_routing_checkbox_set_not_set.json, test_schemas/en/test_routing_group.json, test_schemas/en/test_skip_condition.json, test_schemas/en/test_skip_condition_block.json, test_schemas/en/test_skip_condition_group.json, test_schemas/en/test_skip_condition_not_set.json, test_schemas/en/test_skip_condition_set.json, test_schemas/en/test_submit_with_custom_submission_text.json, test_schemas/en/test_textfield.json
Empty routing rule lists will currently break validator. This removes them
Make sure it works with the latest version of validator
=> Remove empty routing rules lists

app/helpers/template_helpers.py, app/routes/session.py, tests/app/helpers/test_template_helpers.py, tests/app/questionnaire/test_questionnaire_submission.py, tests/functional/spec/custom_page_titles.spec.js, tests/functional/spec/features/conditional_question_title/conditional_checkbox_title.spec.js, tests/functional/spec/features/hub_and_spoke/hub_and_spoke.spec.js, tests/functional/spec/features/repeating_sections/repeating_sections_with_hub_and_spoke.spec.js, tests/integration/individual_response/test_individual_response.py, tests/integration/questionnaire/test_questionnaire_custom_page_titles.py, tests/integration/questionnaire/test_questionnaire_page_titles.py, tests/integration/questionnaire/test_questionnaire_plurals.py, tests/integration/routes/test_confirmation_email.py, tests/integration/routes/test_cookie.py, tests/integration/routes/test_feedback.py, tests/integration/session/test_timeout.py
The recent refactoring of template helpers in https://github.com/ONSdigital/eq-questionnaire-runner/pull/601 broke the survey title for non-census questionnaires. This pull request fixes it.
To fix the issue the survey title has been added to the cookie on authentication. Although this doesn't align with the decision to not store schema properties in the cookie (https://github.com/ONSdigital/eq-questionnaire-runner/blob/master/doc/architecture/decisions/0010-cookies.md), that would require wider changes to ensure the schema is always in scope when we have a session cookie, and should be done separately.
Check that the page title and page header title contain the survey title for non-census questionnaires.
=> Fix survey title in header and page title

yarn.lock
This PR upgrades `yarn.lock` packages to their latest version to prevent dependabot PRs from appearing. Change is described on [this Trello](https://trello.com/c/iAFJg2TU).
Check if all the scripts and functional tests are working as expected.
=> Update Javascript packages

app/views/handlers/submission.py, tests/app/views/handlers/test_submission_handler.py
This PR reintroduces view_submitted_response, which if true means the question store is not deleted on submission
I haven't added an integration/functional test or a schema, but I have tested the handler. My theory is until we have the feature that allows the visualisation of answers on post submission, there isn't a great deal to test integration/functional wise. We already have a test that checks the store is deleted so don't need to check that again, just that it is being called or not
=> Add view_submitted_response to submission handler

.github/workflows/master.yml, .github/workflows/pull_request.yml
This reintroduces `Push to GCR` task to both `pull-request` and `master` workflows. New service account with `Storage Legacy Bucket Reader`(storage.buckets.get, storage.objects.list, storage.multipartUploads.list) and `Storage Object Admin` roles was created in the gcp project. This change requires two new secrets to be added to the repository: `GCLOUD_SERVICE_KEY` and `GCLOUD_PROJECT_ID`. This has been tested in [this fork of launcher](https://github.com/petechd/eq-questionnaire-launcher/pulls). Container Registry with pushed images can be found [here](https://console.cloud.google.com/gcr/images/pete-test-env-on-release).
EDIT: These Runner and Launcher PRs are now pushing images tagged with branch name to our dev repository too.
- Fork the repository 
- in gcp (your project) create new …
=> Push to GCR on PRs

app/data_models/answer.py, app/data_models/answer_store.py, app/libs/utils.py, app/questionnaire/placeholder_parser.py, app/questionnaire/questionnaire_schema.py, app/questionnaire/rules.py, app/questionnaire/value_source_resolver.py, mypy.ini, tests/app/data_model/test_answer.py, tests/app/data_model/test_answer_store.py, tests/app/forms/field_handlers/test_date_handler.py, tests/app/libs/test_utils.py, tests/app/questionnaire/conftest.py, tests/app/questionnaire/test_placeholder_parser.py, tests/app/questionnaire/test_questionnaire_schema.py, tests/app/questionnaire/test_rules.py, tests/app/questionnaire/test_value_source_resolver.py
Added a new `ValueSourceResolver` interface since we now need the ability to resolve value sources both in placeholders and the new when rules. Placeholders have been refactored to use this new interface. Field handlers define its own way of resolving value sources which should be removed and replaced with `ValueSourceResolver` as a future piece of work. Field handlers were not refactored in this PR to keep these changes to a minimum and because they require additional work to add support for list stores etc.
For placeholders, values are escaped and for routing we perform operation on unescaped values, therefore I have left it up to the caller to escape the values instead of making it the responsibility of `ValueSourceResolver` as it give the freedom to the caller to escape as they …
=> Introduce a common interface for resolving value sources

app/jinja_filters.py, app/translations/messages.pot, app/views/handlers/feedback.py, templates/feedback.html, templates/partials/answers/address.html, templates/partials/answers/currency.html, templates/partials/answers/date.html, templates/partials/answers/duration.html, templates/partials/answers/mobilenumber.html, templates/partials/answers/number.html, templates/partials/answers/percentage.html, templates/partials/answers/radio.html, templates/partials/answers/relationship.html, templates/partials/answers/textarea.html, templates/partials/answers/textfield.html, templates/partials/answers/unit.html, templates/partials/question.html, tests/app/test_jinja_filters.py, tests/functional/base_pages/feedback.page.js, tests/functional/spec/dates.spec.js, tests/functional/spec/feedback.spec.js
The design system components now have a `legendIsQuestionTitle` that removes the need for duplicating the question title (visually hidden) into the answer legend. The rules for when this apply are documented at https://ons-design-system.netlify.app/patterns/question/.
This pull request implements the logic for everything except `Checkbox` answers. `Checkbox` answers don't allow for defining the `legend` at the schema level - we use the `label` schema property to populate the `checkboxesLabel` in the design system macro. This is being looked at by the design system team, and will likely require a new schema property to allow both a label and some kind of instruction (e.g. "Select all that apply").
- Review the changes and use the appropriate test schemas to test
- The question title should …
=> Use question title as legend

app/data_models/app_models.py, app/views/handlers/submission.py, tests/app/storage/test_encrypted_questionnaire_storage.py
After issues with purging questionnaire state using datetime this PR changes submitted_at to a timestamp. As our current timestamp doesn't use milliseconds and submitted_at is also included in the payload it was decided to remove  the milliseconds on submission.py
Check the change works, locally or on GCP if you like (I did do both)
=> Update submitted_at to timestamp

app/views/contexts/thank_you_context.py, app/views/handlers/thank_you.py, scripts/run_validator.sh, templates/thank-you.html, test_schemas/en/test_thank_you.json, tests/app/views/contexts/test_thank_you_context.py, tests/integration/routes/test_thank_you.py
Uses the new `post_submission.guidance` schema property to override thank you page guidance.
- Use the new `test_thank_you` schema to verify the new functionality
- Use another default theme survey to verify the existing runner default guidance still works
=> Use schema defined post submission guidance on thank you page

app/settings.py
This fixes incorrect cdn assets path when environmental variable from `.development.env` file is not used and settings.py fallback option is picked instead.
Check if assets are pulled from cdn when not using environmental variable (eg. using local runner instance).
=> Fix cdn path for design system assets

templates/view-submitted-response.html, tests/functional/base_pages/view_submitted_response_base.page.js, tests/functional/spec/features/view_submitted_response/view_submitted_response.js
Adds a `Print answers` button to the `view-submitted-response` page.
Use the `test_view_submitted_response` schema to test this change
=> Add print button to the view submitted response page

README.md
As a new starter, there was a missing step to create the file `.application-version` required by the app to run. Without this step to create the file, unittests in `tests/app/test_app_init.py` fail,
- Follow the instructions in the readme to create `.application-version`
- Run `make link-development-env` 
- Run `make test-unit` and expect them to pass. 
Without the step to create the file, unittests in `tests/app/test_app_init.py` fail
* [] New static content marked up for translation
* [] Newly defined schema content included in eq-translations repo
=> Adds instruction to create .application-version on cloned repo; tidying for markdown linter

test_schemas/en/test_new_routing_and.json, test_schemas/en/test_new_routing_not.json, test_schemas/en/test_new_routing_or.json, tests/functional/spec/features/routing/and.spec.js, tests/functional/spec/features/routing/not.spec.js, tests/functional/spec/features/routing/or.spec.js
Adds the new routing rules schemas and functional tests for the `and`, `or` and `not` operators.
Make sure the new schemas and functional tests work
=> Add new routing and or and not operators

app/questionnaire/placeholder_parser.py, app/questionnaire/placeholder_renderer.py, app/questionnaire/placeholder_transforms.py, app/views/contexts/context.py, app/views/contexts/section_summary_context.py, app/views/contexts/summary/group.py, app/views/handlers/block.py, app/views/handlers/individual_response.py, mypy.ini, tests/app/forms/test_questionnaire_form.py, tests/app/questionnaire/conftest.py, tests/app/questionnaire/test_placeholder_parser.py, tests/app/questionnaire/test_placeholder_renderer.py, tests/app/questionnaire/test_placeholder_transforms.py
Typing has been added to placeholders. The defaults have also been removed, so the stores are now always passed +schema
Confirm that typing is correct (in places it could be allowing too many) and make sure every works as before with placeholders
=> Add Type hinting to placeholders and remove default stores

app/forms/duration_form.py, app/forms/field_handlers/field_handler.py, app/forms/field_handlers/number_handler.py, app/forms/questionnaire_form.py, app/forms/validators.py, app/jinja_filters.py, mypy.ini, tests/app/forms/field_handlers/test_address_handler.py, tests/app/forms/field_handlers/test_date_handler.py, tests/app/forms/field_handlers/test_dropdown_handler.py, tests/app/forms/field_handlers/test_duration_handler.py, tests/app/forms/field_handlers/test_field_handler.py, tests/app/forms/field_handlers/test_mobile_number_handler.py, tests/app/forms/field_handlers/test_month_year_date_handler.py, tests/app/forms/field_handlers/test_number_handler.py, tests/app/forms/field_handlers/test_select_handler.py, tests/app/forms/field_handlers/test_select_multiple_handler.py, tests/app/forms/field_handlers/test_string_handler.py, tests/app/forms/field_handlers/test_text_area_handler.py, tests/app/forms/field_handlers/test_year_date_handler.py, tests/app/forms/validation/test_number_range_validator.py
- Add type hints to `app/forms/validators.py` , `app/forms/duration_form.py` 
- `error_messages` are not optional to `FieldHandler` class
-  Updated unit test to pass `error_messages` `dict`
- Add unit tests to reflect code changes and have 100% code coverage due to typing
companion PR adding type hints to the other modules in `forms` is https://github.com/ONSdigital/eq-questionnaire-runner/pull/665
Run the python linter and unit tests to ensure nothing is broken. Verify where code has changed to accommodate the typing errors(raised by mypy) and previous types were updated.
=> Add type hint form module - validtors.py and duration_form.py

tests/functional/spec/features/routing/date.spec.js
There is a bug in our functional tests which relies on adding 1 or taking it away from the day, naturally this will fail on the first or last day of a month
Check this has been update correctly and passes
=> Fix functional test bug in dates with first and last day of month

.gitignore, app/data_models/__init__.py, app/forms/address_form.py, app/forms/email_form.py, app/forms/field_handlers/address_handler.py, app/forms/field_handlers/date_handlers.py, app/forms/field_handlers/duration_handler.py, app/forms/field_handlers/field_handler.py, app/forms/field_handlers/number_handler.py, app/forms/questionnaire_form.py, app/forms/validators.py, app/questionnaire/__init__.py, app/questionnaire/questionnaire_schema.py, app/views/handlers/confirm_email.py, app/views/handlers/question.py, mypy.ini, tests/app/forms/test_questionnaire_form.py
Adds type hints to `apps/forms/address_form.py`, `apps/forms/email_form.py`, `apps/forms/questionnaire_form.py` to ease development and identify issues with incompatible types earlier. 
Companion PR, adding type hints to the other modules in `forms`: https://github.com/ONSdigital/eq-questionnaire-runner/pull/668
Run unit tests (most importantly mypy) to show no breakage and that types used are all correct. Reviewers to check the more complicated types like nested dicts/lists if they happen to know the code already.
=> Add type hints for forms modules `address_form.py`, `email_form.py`, `questionnaire_form.py`

app/submitter/submitter.py, app/views/handlers/feedback.py, tests/app/submitter/test_submitter.py
Feedback metadata was being updated after encryption meaning this would break using GCSFeedbackSubmitter, this moves if before encryption
Check locally and on GCP feedback now works
=> Move feedback metadata update before encryption

app/authentication/authenticator.py, app/routes/session.py, tests/app/authentication/test_authenticator.py, tests/integration/integration_test_case.py, tests/integration/routes/test_session.py
The /session-expiry endpoints needed to be provided for PATCH and GET; PATCH will extend the session and return the updated expires_at value, GET will not extend the session and return the current expires_at value.
- Launch a survey
- Within 1 min, go to http://localhost:5000/session-expiry to show the GET request returns the initial expires_at timestamp
- Also within 1 min, run this command from chrome dev tools to show the PATCH request returns the inital expires_at timestamp 
```
fetch('http://localhost:5000/session-expiry', {
method: 'PATCH',
headers: {
'Content-type': 'application/json; charset=UTF-8'
}
})
.then(res => res.json())
.then(console.log)
```
- Wait for longer than 1 min
- Go to http://localhost:5000/session-expiry again to show the GET endpoint doesn't update the …
=> Conditionally extend session from PATCH/GET /session-expiry

app/questionnaire/router.py, app/questionnaire/routing/when_rule_evaluator.py, test_schemas/en/test_new_hub_section_required_and_enabled.json, test_schemas/en/test_new_routing_to_questionnaire_end_multiple_sections.json, test_schemas/en/test_new_section_enabled_checkbox.json, test_schemas/en/test_new_section_enabled_hub.json, test_schemas/en/test_new_section_enabled_radio.json, tests/app/questionnaire/test_router.py, tests/functional/spec/features/enabled-sections/enabled_section_checkbox.spec.js, tests/functional/spec/features/enabled-sections/enabled_section_hub.spec.js, tests/functional/spec/features/enabled-sections/enabled_section_radio.spec.js, tests/integration/questionnaire/test_questionnaire_hub.py, tests/integration/session/test_sign_out_and_exit.py
This adds new rules engine for the section enabled element of schemas, based on element type it will now evaluate `when` rules using old or new when rule evaluation. All schemas that use that used old type of when rules in section enabled has been updated and added to schemas with `new` prefix.
Run new test schemas manually or run unit tests.
=> Add new rules engine for section enabled rules

app/questionnaire/placeholder_transforms.py, app/questionnaire/routing/operations.py, app/questionnaire/routing/operator.py, app/questionnaire/routing/when_rule_evaluator.py, tests/app/questionnaire/routing/test_operators.py
Make operations into a class, and move instantiated higher. The instantiation has been moved higher to allow access to schema etc, but at present that is not implemented and on a different card
Make sure everything still works
=> Refactor operations.py into class

docker-compose-schema-validator.yml, scripts/run_validator.sh, scripts/validate_test_schemas.sh, test_schemas/en/test_new_routing_and.json, test_schemas/en/test_new_routing_or.json
- Introduce new docker-compose file for validator.
- update run validator script to use new docker-compose
- update `validate_test_schema.sh` script to check for AJV service status instead of Python validator service
- Fix failing schema
- [Validator PR for this change ](https://github.com/ONSdigital/eq-questionnaire-validator/pull/128)
Run validator and validate test schema, ensure all schemas are passing
=> Add schema validator compose file

app/forms/questionnaire_form.py, tests/app/forms/test_questionnaire_form.py
This PR fixes period limits when minimum is not set. We were checking an object which could be None and therefore it was falling over. Our code just needed a tweak and min_offset = self._get_offset_value moved inside the initial part of the if
Make sure I have fixed it properly. You could lift the json from the test and put it in a schema (test_date_range is probably easiest) and try it if you like. You could also try lcree_0010.json if you want to use the schema that fell over because of it. It will be available in launcher (assuming you have .schemas-version >=v3.0.2)
=> Fix period limits when minimum not set

app/translations/messages.pot, templates/layouts/configs/_save-sign-out-button.html, tests/functional/spec/save_sign_out.spec.js
Fixes the missing exit button link on the introduction page.
- Launch `test_introduction.json`
- Ensure when you click `Exit` you are signed out and taken to the log-out URL.
=> Fix exit button link on introduction page

tests/app/forms/validation/conftest.py, tests/app/forms/validation/test_date_check_validator.py, tests/app/forms/validation/test_date_range_validator.py, tests/app/forms/validation/test_date_required.py
This PR updates the tests for forms validation for DateCheck, DateRequired and DateRangeCheck to pytest. Extra tests have been added as coverage was missing from the original and some have been removed as I thought they weren't overly useful
Firstly check coverage of just these new tests now has line coverage for the correct parts in validators.py. I quite like updating scripts/run_tests_unit.sh  (i.e py.test ...... -k test_date_check_validator) and then looking at htmlcov/index.html in a browser to see coverage. (there are other ways of course)
Once that has been done check that everything has been updated to pytest correctly.
=> Update form validation dates to pytest and fix coverage

tests/functional/spec/features/validation/sum/sum_equal_or_less_validation_against_total.spec.js, tests/functional/spec/theme_northernireland.spec.js
This adds another batch of functional tests for schemas.
Functional tests already exist for:
- `test_submit_with_summary`
- `test_submit_with_summary_custom_submission_text`
- `test_theme_social`
- `test_view_submitted_response`
Test for `test_sum_equal_or_less_validation_against_total` already exists but needed fixing as it was referencing wrong schema and assertions were incorrect.
Only new test added is for `test_theme_northernireland`.
Check new test and the existing, fixed one.
=> Add functional tests batch 4

tests/app/forms/test_duration_form.py, tests/app/forms/validation/test_mobile_number_validation.py, tests/app/forms/validation/test_mutually_exclusive_validator.py, tests/app/forms/validation/test_number_range_validator.py, tests/app/forms/validation/test_number_validator.py, tests/app/forms/validation/test_response_required.py, tests/app/forms/validation/test_single_date_range_validator.py, tests/app/forms/validation/test_sum_check_validator.py, tests/app/helpers/test_template_helpers.py, tests/app/questionnaire/rules/test_operation_helper.py, tests/app/questionnaire/test_date_rules.py, tests/app/questionnaire/test_dynamic_answer_options.py, tests/app/questionnaire/test_path_finder.py, tests/app/questionnaire/test_placeholder_transforms.py, tests/app/questionnaire/test_plural_forms.py, tests/app/questionnaire/test_questionnaire_store_updater.py, tests/app/questionnaire/test_when_rules.py, tests/app/schema_loader/test_schema_loader.py, tests/app/storage/test_encrypted_questionnaire_storage.py, tests/app/storage/test_storage_encryption.py, tests/app/utilities/test_strings.py
This updates pytest parametrized arguments to contain spaces for readability (eq. `mandatory, years, months, valid, error` instead of `mandatory,years,months,valid,error`).
Check that all arguments are correctly formatted.
=> Update pytest parametrized arguments to contain spaces

app/authentication/jti_claim_storage.py, app/globals.py, app/helpers/address_lookup_api_helper.py, app/helpers/header_helpers.py, app/helpers/language_helper.py, app/helpers/schema_helpers.py, app/helpers/session_helpers.py, app/helpers/url_safe_serializer.py, app/helpers/uuid_helper.py, mypy.ini, tests/app/conftest.py, tests/app/data_model/test_fulfilment_request.py, tests/app/helpers/conftest.py, tests/app/helpers/test_address_lookup_api_helper.py, tests/app/helpers/test_schema_helper.py, tests/app/libs/test_utils.py, tests/app/views/handlers/test_individual_response_fulfilment_request.py
Added type hints to the helpers module.
Ensure the type annotations are accurate.
Note: Decorator type hints return `Any` due to a lack of support by the language. It has been improved in Py 3.10, therefore, we can properly type check decorators once we are on Py 3.10 using [ParamSpec]( https://peps.python.org/pep-0612/).
=> Add type hints to helpers

app/questionnaire/questionnaire_schema.py, schemas/test/en/test_numbers.json, tests/app/questionnaire/conftest.py, tests/app/questionnaire/test_questionnaire_schema.py, tests/functional/spec/numbers.spec.js, tests/functional/spec/save_sign_out.spec.js
This PR adds answer dependencies for min and max validation
Using test_numbers.json, complete the survey then go back and change set min/max (first block). Make sure you have to confirm/validate any answers again that have dependencies before going back to summary, the best one to change is max as it has dependencies on the other 2 blocks in the questionnaire
=> Answer dependencies for min and max validation

templates/calculatedsummary.html
The calculated summary is currently using a success panel style (green) for what should be an information panel (blue), have extra padding at the beginning of the text and have a class (`print__hidden`) that isn't being used. Also removes the full stop as this is not needed when the panel only has one line.
This PR will fix these issues
- Test calculated summaries and see that the panel is now blue and the text doesn't have the extra padding at the beginning
=> Fix info panel style on calculated summaries

templates/layouts/_questionnaire.html, templates/partials/email-form.html, tests/functional/spec/features/validation/date_validation/date-combined-yyyy.spec.js, tests/functional/wdio.conf.js
Fixes issue with save and continue button that has too big a margin top on it.
Also removes a `ons-u-mb-xl` that is not needed too.
This PR also updates the wdio config to make the resolution 4k. This is because updating this bit by bit has caused issues in the tests. Updating in to a 4k resolution should stop anymore issues
- Check a few schemas in master and on this branch to see the button is now spaced correctly (`test_numbers`, `test_dates` are two good ones)
- Check `test_confirmation_email` see the gap underneath the button is reduced
=> Fix save and continue button spacing

app/views/contexts/thank_you_context.py
There is currently a bug with countdown panels not showing the countdown on IE11. This is because the time being passed to the panel from runner is not in ISO format which IE11 seems to be struggling with. This PR will convert the time being passed to the panel to ISO format.
- Tests pass
- Panel still works as it should when used in the `test_view_submitted_response` schema
=> Fix IE11 countdown panel bug

app/translations/messages.pot, templates/layouts/_base.html
This removes old census cookie banner url and replaces it with a RAS one, requirement described on [this Trello card](https://trello.com/c/7roDKuo1).
Visually check schema's cookie banner after launching.
=> Utilise correct cookie banner url

.github/release.yml
Currently we use inappropriate plural versions of pull request labels, this PR fixes the issue.
Autogenerate release notes on your fork after merging some labelled PRs.
=> Fix labels for autogenerated release notes

app/views/contexts/calculated_summary_context.py, app/views/contexts/summary/answer.py, app/views/contexts/summary/question.py, tests/app/views/contexts/summary/test_answer.py, tests/app/views/contexts/test_calculated_summary_context.py
- Made the `return_to` query string from the change link for Calculated summaries conditional on section summary/hub flow. We currently do not support jumping straight back to a calculated summary. Support for jumping straight back to a calculated summary will be implemented separately.
- Also removed tests in `test_calculated_summary_context.py` that were duplicated from `test_section_summary_context.py`
***Note: This is a temporary solution***
Ensure the change links on a calculated summary depend on the whether you have a section summary and or if hub is enabled.
- if section summary is enabled for the section you are on, then return to should be `section-summary`
- if section summary is disabled and hub is disabled, then return to should be `final-summary`
- otherwise, return to …
=> Make calculated summary return_to conditional

app/survey_config/business_config.py, tests/app/helpers/test_template_helpers.py, tests/integration/test_header_links.py
- Temporary tactical solution to only send RAS the first 11 characters of the `ru_ref` when generating the help link. The first 11 characters are send because the reporting unit reference is always 11 characters.
- The `ru_ref` eQ gets from RAS actually includes `ru_ref` + `check_letter` but when using the help link, they do not expect the `check_letter` to be present. They will progress a more appropriate solution to their end in the future, but this is a temp fix to get the changes in preprod moving.
- Launch a schema and set the ru ref to your liking, and ensure that only the first 11 characters are used when generating the help link ru_ref query param.
=> Bug fix: Only include first 11 characters of ru_ref in help link

app/views/contexts/calculated_summary_context.py, app/views/handlers/calculated_summary.py, tests/functional/spec/features/calculated_summary.spec.js
Page title was not being set for Calculated summary blocks.
Ensure the page title is set appropriately. The title for calculated summary should be `{calculated_summary_title} - {survey_title}`. Ensure the title does not display `None`.
- Test using any schema with a calculated summary.
=> Set page title for Calculated summary blocks

app/data_models/session_data.py, tests/app/data_model/test_session_data.py, tests/app/data_model/test_session_store.py
Recently `schema_url` was introduced in favour of `survey_url`, however that breaks in-flight sessions for users that currently made use of `survey_url`.
- This PR adds supports so that in-flight session does not error when rolling out the `schema_url` change. 
- Although `survey_url` is now supported for in-flight sessions, the literal value for `survey_url` has been dropped. RAS does not use `survey_url` for any live surveys.
- With this change `SessionData` accepts a `schema_url` or `survey_url` on initialisation. This was simply to allows us to roll back this change in the event this errored in prod. Once `schema_url` has been rolled out successfully, `survey_url` will be removed in a subsequent PR.
1. Check out to v3.107.1 and launch a survey
2. Check out to this branch and try to …
=> Bug fix: Support for in-flight sessions that use survey_url

app/submitter/convert_payload_0_0_1.py, tests/app/submitter/test_convert_payload_0_0_1.py
Identified a bug on submission in our `covert_payload_0_0_1.py` while testing the BICS survey. When a user selected a detail answer field but did not set an answer, we were getting a 500 error as `detail_answer.value` could not be resolved as the value the `detail_answer` was  a `None` type.
Added a check to ensure that the `detail_answer` was not a None type before getting the value.
Check all tests pass.
=> Fix detail answer value bug in convert_payload_0_0_1

app/forms/questionnaire_form.py, app/questionnaire/__init__.py, app/questionnaire/questionnaire_schema.py, app/submitter/convert_payload_0_0_1.py, app/views/handlers/confirm_email.py, schemas/test/en/test_checkbox.json, tests/app/submitter/test_convert_payload_0_0_1.py
Radio details answer was being ignored for data version 0.0.1. This PR ensure details answer for radios are in the downstream payload.
- Test with a schema that has a radio detail answer, i.e `covid_001`.
- Complete the first section
- For the "Exporting" section, for answers "Other" and enter a detail answer
- Once on the hub, try a submission via `/dump/submission` and ensure the `Other` value and it's user entered detail answers are in the payload.
=> Bug fix: Support radio detail answer for data version 0.0.1

package.json, yarn.lock
When running `yarn` to update js dependancies this warning appears
This PR will install typescript to remove this warning
Run `yarn` on master see warning
Run `yarn` on this branch see warning is gone
=> Fix yarn typescript warning

templates/partials/answers/percentage.html, tests/integration/components/test_render_percentage_widget.py
Percentage symbol is missing from the suffix on `test_percentage` schema
Open the `test_percentage` schema and see that the percentage symbol suffix is displayed
=> Fix percentage symbol missing on input

app/routes/session.py, tests/integration/routes/test_session.py
This fixes the way we render `session-expired` page that uses `401.html` template. The correct way is to use the `_render_error_page()` method for all error pages (that creates all the required vars) instead of ordinary `render_template()`.
Two new assertions added that check if required urls exists.
=> Fix session expired page links

app/routes/session.py, schemas/test/en/test_theme_health.json, schemas/test/en/test_theme_social.json, tests/app/parser/conftest.py, tests/app/parser/test_metadata_parser.py, tests/app/submitter/test_submitter.py, tests/app/views/handlers/test_feedback_upload.py, tests/functional/jwt_helper.js, tests/integration/create_token.py
The property `questionnaire_id` has been renamed to `qid` as part of https://github.com/ONSdigital/ons-schema-definitions/pull/71
Ensure all instances have been renamed.
=> Rename questionnaire_id to qid

schemas/test/en/test_theme_health.json, schemas/test/en/test_theme_social.json
Removes case_ref from Social/Health schema as they are not required fields.
=> Remove case_ref from Social/Health schemas

app/questionnaire/router.py, schemas/test/en/test_calculated_summary_dependent_questions.json, tests/app/questionnaire/test_router.py
Fixes a bug where users were seeing a 404 page when attempting to return to a calculated summary page. This was because we were attempting to return to the calculated summary page before visiting dependent questions.
Updated the logic so that we only return to the calculated summary page when all dependent questions are complete.
Added a test with a new `test_calculated_summary_dependent_questions` schema which emulates the journey that resulted in the bug.
Updated bug in journeys in the existing calculated summary tests.
Check that you see any dependent questions before returning to a calculated summary page, and that a `404` page is no longer displayed.
Use the `test_calculated_summary_dependent_questions`:
Complete all questions -> Use the change link on the second question on the …
=> Evaluate calculated summary is complete when returning to a calculated summary

app/translations/messages.pot, tests/functional/spec/features/confirmation_question_within_repeating_section.spec.js
Bug fix for functional tests Confirmation Question Within A Repeating Section now that the year is 2023. If the year in the test is longer than 15 years from the current date then the dob question will not route to the confirmation question once answered which breaks the test. The discussion on whether this should be a dynamic number has not come up with another solution and any solution to create the date dynamically could cause the test to be flakey.
Test now passes
=> Update year in test to fix new year bug

app/views/contexts/summary/group.py, schemas/test/en/test_new_calculated_summary_repeating_section.json, tests/functional/spec/features/new_calculated_summary_repeating_section.spec.js
Fixes an issue where if a calculated summary included an answer which had a title that referenced another calculated summary's total, the value was being piped as 0.
Use the `test_new_calculated_summary_repeating_section` schema to test the change.
Steps to recreate:
Get to the Number Total Playback page -> Answer the breakdown question -> Get to the Second Currency Total Playback page -> Check the value of the placeholder for the is correct on the page in the sentence: `Enter two values that add up to the previous calculated summary total of £x`
On master the value will be £0
=> Bug: Placeholders referencing an incorrect calculated summary value in another calculated summary in a repeating section

app/routes/flush.py, tests/integration/test_flush_data.py
> Currently v2 flushes are using v1 converter. Added a condition to check the metadata for flush accordingly.
[Trello](https://trello.com/c/mqAs98GC/5556-phm-flush-using-v1-instead-of-v2-which-is-failing-over-validating-in-sdx)
> Use the launcher to check if the v2 flush is using v2 converter
**Comment From Developer**
I was not sure how to test this change, the unit tests covers the actual convertors already. Hence used mock to just insure that the appropriate converter is called based on the launch version selected.
=> Bug: Flush always using v1 converter

app/questionnaire/router.py, app/views/handlers/list_action.py, app/views/handlers/list_add_question.py, app/views/handlers/list_collector.py, app/views/handlers/list_remove_question.py, app/views/handlers/question.py, schemas/test/en/test_list_collector_section_summary.json, tests/functional/spec/features/repeating_sections/repeating_sections_with_hub_and_spoke.spec.js, tests/functional/spec/list_collector.spec.js, tests/functional/spec/list_collector_section_summary.spec.js, tests/integration/questionnaire/test_questionnaire_list_change_evaluates_sections.py, tests/integration/questionnaire/test_questionnaire_list_collector.py
In a schema with a list collector and a summary, when the user completes the list collector block and lands on the summary page, but then adds another item to the list, they are redirected to the summary.
Instead, we want the user to be redirected to the list collector parent page, asking them if they want to add another item to the list collector.
This change also impacts the `change` and `remove` actions.
Thus here are the specs:
* If the user adds from the summary, return to the parent location
* If the user changes an item from the summary, return to the summary
* If the user removes an item from the summary:
* if the change of list length introduces a new incomplete block, redirect to this block
* Otherwise, go back to the summary 
Smoke tests on the list collector schemas.
Changes …
=> Fix bug: add to list is returning straight back to summary

schemas/test/en/test_list_collector_section_summary.json
> As a part of the [this fix](https://github.com/ONSdigital/eq-questionnaire-validator/pull/176), the schema tests were failing on runner due to the added validation. This PR updates the schema to fix the failing tests.
> Make sure all schema test passes.
=> Bug: Answer codes validation skips validation-schema fix

templates/layouts/_base.html, tests/functional/spec/page_layout.spec.js
DS V62 sets the default width to 12 columns, this PR sets it to 8 to as that is what runner requires. This was regressed in https://github.com/ONSdigital/eq-questionnaire-runner/pull/1029
Although this is a UI change which we don't normally test, I have added an assertion which checks the width using the CSS class. Although this couples the test with the DS classes, this change is too important to regress.
Ensure the width for pages in runner look as expected.
=> Bug: Runner page width set to 12 columns

schemas/test/en/test_thank_you_census_household.json
The recent change to the validator suggests if the questionnaire_flow properties type is  constant `Hub` each section should have `required title`. The corresponding fix was a part of https://github.com/ONSdigital/eq-questionnaire-runner/pull/996/files PR which still need to be merged. Hence having this fix.
Test schema validation is passing.
=> Fixing validation schema failure due to missing title

app/helpers/language_helper.py, app/helpers/template_helpers.py, app/routes/session.py, app/setup.py, tests/app/helpers/test_template_helpers.py, tests/integration/routes/test_cookie.py, tests/integration/routes/test_questionnaire_language.py
Currently, when in Welsh the signed-out page (sign out confirmation) does not display all text in Welsh. This PR
adds all necessary changes, cookie session is being used to store the language now, it is being used by `get_locale` method in schema utilities etc.
Launch test_language schema, switch to Welsh, click Save and Exit survey. Sign out confirmation should have all its contents in Welsh. Check new test and expanded cookie test.
=> Fix signed-out confirmation in other languages

app/translations/messages.pot, babel.cfg, templates/layouts/_base.html, templates/layouts/_questionnaire.html, tests/functional/base_pages/base.page.js, tests/functional/spec/cookie_banner.spec.js
Sets the language code on cookie banners and adds the babel extension to the babel config to prevent the cookie banner strings from being ignored by translations.
Also removes an import that isn't being used.
- Clear your cookies, load test_language schema, switch to Welsh and see that the cookie banner buttons will change to Welsh.
- Test this in comparison to the `main` branch
=> Update cookie banner to be multilingual

app/routes/flush.py, tests/integration/test_flush_data.py
This binds new context vars to our logs on flush requests. New values are exercise id, schema name and schema url where applicable. 
Two new unit tests added to test both logs with and without `schema_url` present.
=> Bind additional contexts to flush requests

app/authentication/authenticator.py, app/data_models/answer_store.py, app/data_models/list_store.py, app/data_models/questionnaire_store.py, app/data_models/supplementary_data_store.py, app/questionnaire/questionnaire_store_updater.py, app/routes/session.py, app/submitter/converter.py, app/submitter/converter_v2.py, tests/app/conftest.py, tests/app/data_model/conftest.py, tests/app/data_model/test_answer_store.py, tests/app/data_model/test_list_store.py, tests/app/data_model/test_questionnaire_store.py, tests/app/data_model/test_supplementary_data_store.py, tests/app/submitter/conftest.py, tests/app/submitter/test_convert_payload_0_0_1.py, tests/app/submitter/test_convert_payload_0_0_3.py, tests/integration/routes/test_session.py
This PR implements the creation of the new supplementary data store and the loading of sds data into that store whenever a new questionnaire session is launched (and any existing supplementary dataset id doesn't match)
It handles removing old supplementary data if the new data is different (or there is no new data) and creating or updating the list store for any supplementary data lists.
This is part of the **Loading of supplementary data** card and implements the functionality, along with a simple test for the store, but no other testing yet.
The supplementary data, ideally will be fetched in `session.py` however this needs to happen between the store being created/fetched from storage and the metadata for it being overridden, which all happens in the authenticator. Since it needs the …
=> Create supplementary data store

app/jinja_filters.py, tests/app/test_jinja_filters.py
`mass-metric-ton` is no longer supported for `en_GB` and related locales, but still present in business schema and allowed in validator. Until removed from schema and validator definitions we want to substitute `mass-ton` for `mass-metric-ton` and vice versa, before and after unit formatting.
New test cases in existing unit tests.
=> Fix `mass-metric-ton` units handling

app/views/handlers/list_action.py, app/views/handlers/list_repeating_question.py
This removes `update_section_completeness` call that adds list items progress for child blocks which wasn't done in the past and wasn't required for looping 3.5. The only time childs are used is for repeating blocks.
Check that all tests still pass.
=> Remove update_section_completeness call in list actions

app/routes/session.py, tests/integration/create_token.py, tests/integration/questionnaire/test_questionnaire_locale.py
This PR implements a fix for answer type `mass-metric-tonnes` displaying the tooltip of "metric tons" when it should be "tonnes" regardless of whether the language being set is "en" or "en_GB". 
A fix was implemented in a previous PR to ensure `get_locale` returns "en_GB" instead of "en" when "en" is set as the `language_code`. This however assumed there would always be a `language_code` set, if `None` is provided as the `language_code`, `get_locale` will return "en".
This PR fixes this issue by ensuring `None` `language_code` defaults to `DEFAULT_LANGUAGE_CODE` (en).
**session.py**: `cookie_session["language_code"]` defaults to `DEFAULT_LANGUAGE_CODE` if `metadata.language_code` is `None`.
**create_token.py**: New integration test helper method `create_token_v2_with_none_language_code` …
=> Bug Fix: None language code defaults to "en"

app/setup.py, tests/integration/test_app_create.py
Following the move to Google Analytics 4, our CSP policy needs updating as per the docs here: https://developers.google.com/tag-platform/tag-manager/csp
Deploy a staging env using this branch with GTM enabled or use my staging env [here](https://rhys-staging-2023-08-07-launcher.eq.gcp.onsdigital.uk/).
Check that when using this branch there are no CSP policy violations in the Dev Tools console (compare with the console for our real staging env where errors should be visible, ensure logging is set to Verbose in order to see the violations).
=> Update CSP policy urls for GA4

app/jinja_filters.py, schemas/test/en/test_placeholder_transform.json, schemas/test/en/test_unit_patterns.json, scripts/run_validator.sh, tests/app/test_jinja_filters.py, tests/functional/spec/features/units.spec.js, tests/integration/questionnaire/test_questionnaire_locale.py
This removes metric ton support from runner and update related tests and schemas plus updates to use supported units
in existing schemas.
Existing func/unit/integrations tests are updated. Check if the changes make sense (metric ton) no longer supported.
=> Update valid units and remove metric ton support

README.md
I encountered an issue locally when following the readme to install the dependencies with `pipenv`. The workaround is to follow the guidance [here](https://github.com/andrix/python-snappy#frequently-asked-questions)
Check that the readme change makes sense
=> Tweak README with python-snappy dependency install workaround

tests/functional/spec/exit.spec.js
Functional tests have started failing because https://census.gov.uk/en/start has changed to https://www.ons.gov.uk/census and one of the functional tests is checking for a specific url. This PR is just to update that url. No other changes made since census config is soon to be removed.
All tests pass
=> Fix functional tests to reflect url change

app/setup.py, tests/integration/test_app_create.py
There are some CSP violations present in our latest deploy of runner after we migrated to GA4 and removed `unsafe-inline` keyword from the CSP policy. Removing the unsafe-line is causing issues with the SVG which uses inline styles.
Test that reintroducing the keyword causes these violations to stop in deployed environment.
=> Reintroduce unsafe-inline keyword to style-src of CSP policy

app/questionnaire/router.py, schemas/test/en/test_hub_section_required_with_repeat.json, schemas/test/en/test_hub_section_required_with_repeat_supplementary.json, tests/app/questionnaire/test_router.py, tests/functional/spec/features/hub_and_spoke/hub_and_spoke.spec.js, tests/integration/questionnaire/test_questionnaire_hub.py
Previously the `required_completed_sections` field in our schemas did not work for repeating sections. This change allows the hub to be toggled on/off based the completeness of a repeating section.
Use the `test_hub_section_required_with_repeat` schema, and check that you are only able to access the hub page once you have completed all of the repeating sections. Also added `test_hub_section_required_with_repeat_supplementary` to demo the same functionality with a repeating section that is being populated with a list sourced from supplementary data.
=> Allow the hub to be enabled with repeating sections

.pylintrc, tests/app/data_model/conftest.py, tests/app/helpers/test_template_helpers.py
Updates the `pylintrc` file so that node_modules are ignored, as warnings relating to those files were being output when `make lint-python` was being run.
Removes two pylint ignores that are no longer needed.
Run `make lint-python` and check that there are no issues
=> Ignore node_modules in pylint and fix useless suppression warnings

.github/workflows/pull_request.yml, Makefile, README.md, scripts/run_validator.sh
`docker-compose`  command not being found on GIthub actions. It is due to docker-compose  being a V1 Docker  Compose Command which is now removed. 
This PR fixes this issue by using the V2 command `docker compose` for actions and all of runner.
- Check if Github Actions work with the new Docker Compose
- Check the new Docker Compose command mentioned in the README works as expected. (Make sure you are on compose v2 https://docs.docker.com/compose/migrate/)
- Ensure there are no reference using the old `docker-compose` format.
=> Update to Docker Compose v2

docker-compose-dev-linux.yml, docker-compose-dev-mac.yml, docker-compose-schema-validator.yml, docker-compose.yml
Noticed we are now getting a 'version' is obsolete warning when running `make dev-compose-up` locally. Found out the 'version' line is now considered obsolete from the `docker-compose.yml` file now (Docker version 25.0.5) so I have removed it to fix this warning.
- Run `make dev-compose-up` and check that there are no warnings
- Run `make run-validator` and check that there are no warnings
- Compare this to the main branch when running these commands and you should see warnings
=> Fix version obsolete warning

.github/dependabot.yaml, pyproject.toml
Following a recent PR to pin the babel version to `v2.14.0`, we should temporarily prevent dependabot bumping the minor version to `v2.15.0` until the problem has been resolved because this is causing the build to fail.
Fork this repo and trigger a dependabot PR from this branch - the babel minor version increment should be excluded and the build should pass
=> Ignore babel minor version dependabot bumps for now

.github/workflows/pull_request.yml, Dockerfile, README.md
Our test-unit GitHub action is currently failing because of the dotenv poetry plugin now depends on poetry >= v1.8.3. We are currently running v1.8.2, this PR updates that to v1.8.3.
- GitHub actions pass
- Can run `poetry install` to install dependancies without error
- Can spin up runner and still launch schemas
=> Update to Poetry 1.8.3

app/publisher/publisher.py, tests/app/publisher/test_publisher.py
All of our builds are currently failing due to one test. While we investigate, we'll temporarily remove it. It is not currently in use by any enabled feature in eQ Runner, so this will not have any impact on regression during our investigation
Ensure all other tests still pass
=> Temporarily remove failing unit test

.github/dependabot.yaml
At the moment "babel" ignore exception in Dependabot config is added to the development ecosystem, it needs to be moved to the production one.
Fork the repo with all branches, merge this branch, enable Dependabot, check if prod dependencies PRs raised don't have babel update anymore.
Proof of it working in a fork:
https://github.com/petechd/eq-questionnaire-runner/pull/4
=> Move babel ignore to the prod "pip" ecosystem

.github/workflows/pull_request.yml, tests/functional/spec/features/calculated_summary/new_calculated_summary_repeating_and_static_answers.spec.js
Removes a line from the `new_calculated_summary_repeating_and_static_answers` functional test suite that was leading to flaky test issues. The line removed was not needed, as the schema does not render the Hub page on Launch.
Also removes the npm caches in our Actions workflow as they were added to provide performance benefit but not having any real impact at the moment. It maybe having an adverse affect on our flakyness and we are going to progress a ticket to investigate our npm and actions workflow separately.
Check that the updated test passes.
=> Remove hub submit and npm caches

templates/layouts/_submit.html, templates/thank-you.html
The success panel implementation on the thank you page is currently incorrect and because of this is using the blue information panel for the success message. Like this below:
This PR updates the configuration for the panel to use the `variant` param instead of the previously used `type` param. After this change the panel should use the green success panel with a green tick icon. Like this below:
Test by opening the `test_thank_you` schema and navigating to the thank you page. Compare this branch against main and check that the correct panel is now being used.
=> Fix panel implementation on thank you page

app/questionnaire/questionnaire_schema.py, app/questionnaire/questionnaire_store_updater.py, app/utilities/make_immutable.py, pyproject.toml
This PR removes the ignore rule for Ruff's pyupgrade plugin "UP034" error ("Avoid extraneous parentheses"). It's part of the ongoing task of improving the Python code base by gradually fixing all the remaining issues ignored by the linters.
Check that the rule now applies and the issues in the code were fixed.
=> Remove Ruff ignore rule UP034 (pyupgrade)

app/translations/messages.pot
The translations template `messages.pot` file fails the lint check in the actions workflow which checks for any changes as it still expects to see the year `2024` referenced within the file.
Check the newly updated .pot file is correct and that the lint check passes.
=> Update the messages.pot file for 2025

.github/workflows/pull_request.yml
Pins the version of the Poetry Dotenv plugin to v2.6.1 as versions => 2.7.3 require a minimum version of Poetry 2.0.0 (we currently use v1.8.4). We will look to unpin and resolve any dependency issues separately.
Check that the actions workflow is passing as expected.
=> Pin Poetry dotenv plugin version in our actions workflow

.github/workflows/pull_request.yml
Tiny PR to fix version in comment to allow Dependabot to update correctly.
Double check if google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f is version 2.1.7.
=> Fix versioning in google-github-actions/auth 

.github/workflows/pull_request.yml
This pull request updates the GitHub Actions workflow configuration to address version mismatch issues.  The problem is potentially linked to the setup-python action's cache functionality (https://github.com/actions/setup-python?tab=readme-ov-file#caching-packages-dependencies), which has been reported to malfunction in recent repository issues (https://github.com/actions/setup-python/issues). 
Additionally, the action relies on the @actions/toolkit (https://github.com/actions/toolkit/tree/main/packages/cache#%EF%B8%8F-important-changes), which recently started rolling out significant changes that could be contributing to the issue.  
As part of this pull request, Poetry caching has been removed, and the `setup-python` and `install-poetry` steps have been reordered, aligning them with the …
=> Remove cache from setup-python action

scripts/run_validator.sh
The `run_validator` script used in `make run-validator` only contained the command to start the containers. The script didn't pull the latest images for validator and only ran the containers using images that were stored locally. As a result, it created the problem of incorrect/older images being used when running Validator through Docker.
To address this, I added in a command to retrieve the latest images of Validator from GCP to ensure the latest images are being used.
- Run `make run-validator` and see if it pulls the latest images for validator
- Use `docker images --digests` to see if the SHA of the latest Docker image you pulled matches the latest in GCP
=> Update run_validator to retrieve latest Docker image
